### ISSUE TITLE
Wrong example for multiple add in C#

### ISSUE THREAD

**Issue by erikly** [microsoftgraph/microsoft-graph-devx-api#1006]
I can't make example 2 in C# work, and neither can [this guy](https://stackoverflow.com/questions/62475635/add-users-as-group-members-with-microsoft-graph-api-in-net-core). It seems to work when passing a C# array (e.g. `["https://graph.microsoft.com/v1.0/directoryObjects/{id}"]`) instead of the "stringified" version (e.g. `"[\"https://graph.microsoft.com/v1.0/directoryObjects/{id}\"]"` as the dictionary value. This should probably be reviewed for the "Create group" with members also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Resolved with V5 snippet generation
