### ISSUE TITLE
Missing query option

### ISSUE THREAD

**Issue by alberico-lima** [microsoftgraph/microsoft-graph-devx-api#1007]
Hi, it seems on c# example,  in the section https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http#the-next-round-sample-first-request,  it is missing the query option for deltatoken.

Regards,
Alberico.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccc4222a-4294-ccaa-a241-70e35e68d8b3
* Version Independent ID: a2f2cb54-8d82-a83c-1b2d-a66436953f8b
* Content: [Get incremental changes to events in a calendar view  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http)
* Content Source: [concepts/delta-query-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-events.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by millicentachieng** [comment]
The issue appears to be fixed. @alberico-lima, please reopen otherwise.

```c#
// Code snippets are only available for the latest version. Current version is 5.x

var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Me.CalendarView.Delta.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Skiptoken = "R0usmci39OQxqJrxK4";
	requestConfiguration.Headers.Add("Prefer", "odata.maxpagesize=2");
});
```
