### ISSUE TITLE
Multiple snippets tabs are selected in MS Graph Docs

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-devx-api#1020]
![image](https://user-images.githubusercontent.com/9458079/171841424-a0ab49dd-fbd1-472d-a251-baa6222784bf.png)

**Comment by zengin** [comment]
This is likely a docs rendering bug unless we are not outputting the tabs in markdown format incorrectly. The JavaScript function that updates the links on click events come from here: https://github.com/microsoft/templates.docs.msft/blob/master/scripts/index-docs.js

Unfortunately code is minimized. We should probably reach out to team that owns that script to check if our markdown is in expected format.

**Comment by millicentachieng** [comment]
@zengin, as you've mentioned, this is a docs rendering bug but it's also a requirement that all tab sets in a page should be the same for synchronization. We usually get warnings each time the tab set is not uniform across a page and the docs team had already started adding the missing tabs manually like below.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/25274795/174587887-23837e3d-fa39-429d-a816-abbd279892cc.png">

I've updated API Doctor to ensure that we have matching tab sets in a page.

**Comment by zengin** [comment]
thanks for the detailed information @millicentachieng!
