### ISSUE TITLE
[Snippets] Go and PowerShell `FilterByCurrentUser` snippets don't match HTTP Snippet

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1023]
We generate wrong Go and PowerShell snippets for all `FilterByCurrentUser` OData functions. e.g., Given `GET beta/roleManagement/directory/roleEligibilitySchedules/filterByCurrentUser(on='principal')`, we currently generate the following wrong language snippets:
##### Go
``` go
graphClient.RoleManagement().Directory().RoleEligibilitySchedulesById(&unifiedRoleEligibilityScheduleId).Get()
```
##### PowerShell
``` powershell
Get-MgRoleManagementDirectoryRoleEligibilitySchedule -UnifiedRoleEligibilityScheduleId $unifiedRoleEligibilityScheduleId
```

### To Reproduce
See snippets at https://docs.microsoft.com/en-us/graph/api/unifiedroleeligibilityschedule-filterbycurrentuser?view=graph-rest-beta&tabs=powershell#request.

### Expected behavior
We should generate the following language snippets:
##### Go
``` go
graphClient.RoleManagement().Directory().RoleEligibilitySchedules().FilterByCurrentUser(&on).Get()
```
##### PowerShell
``` powershell
Invoke-MgFilterRoleManagementDirectoryRoleEligibilitySchedule -On $On
```

**Comment by ddyett** [comment]
@timayabi2020 assigning this one to you as it looks like PowerShell is not generating here and Go is fixed.
