### ISSUE TITLE
Csharp Snippet Generation Refactor

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/microsoft-graph-devx-api#1025]
Refactor Csharp Snippet Generation To Use Code [SnippetCodeGraph](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/51342d36b6dbd1faf7091a6923d1196b6b4ddd3f/CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs) Class

**Comment by zengin** [comment]
As discussed in the meeting, I think this should target only the snippets for kiota generated SDKs as OpenAPI conversion assumptions might break the existing OData based snippets. Having two separate ones can also help with supporting generation for Typewriter and Kiota SDKs at the same time.
