### ISSUE TITLE
Java Snippet Generation - OpenAPI

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/microsoft-graph-devx-api#1026]
Refactor Java Snippet Generation To Use Code [SnippetCodeGraph](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/51342d36b6dbd1faf7091a6923d1196b6b4ddd3f/CodeSnippetsReflection.OpenAPI/ModelGraph/SnippetCodeGraph.cs) Class

**Comment by zengin** [comment]
Same argument holds for Java:
https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1025#issuecomment-1159322299

**Comment by isvargasmsft** [comment]
Hello @rkodev, do we have updates on this issue?
