### ISSUE TITLE
Snippet Generation doesn't pick up some Intune docs

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#1030]
**Describe the bug**
This is not a snippet generation bug per se, but because the documentation misses the metadata for example URLs, we are not able to generate some of the Intune snippets.

https://github.com/microsoftgraph/microsoft-graph-docs/blob/03c947ff101c10847f1858b73af87753e82cd56f/api-reference/v1.0/api/intune-apps-deviceappmanagement-get.md?plain=1#L55

**Comment by millicentachieng** [comment]
Intune has introduced the metadata for example URLs. We now have snippets generated for the docs.
