### ISSUE TITLE
Code snippets must be clearer on the version of the SDK

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/microsoft-graph-devx-api#1048]
[Microsoft Graph API reference docs](https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) and [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) provide code snippets given an HTTP call/scenario.
However, just by looking at the code snippet, it's impossible to know which SDK version it is compatible with.

We need to be clear which SDK version is supported in both platforms, Graph API reference docs and Graph Explorer.

Any suggestions on what it should look like? @RabebOthmani @lramosvea

**Comment by lramosvea** [comment]
@maisarissi, @jasonjoh and I had a discussion prior to our offsite about this. One of the things we discussed was having a policy we can publish about versioning, which I think currently does not exist. We need to discuss this also with Seb and Vivian.

**Comment by ddyett** [comment]
@maisarissi @lramosvea do we still need to close on anything here?

**Comment by maisarissi** [comment]
We should have a new sentence highlighting the version used to generate the snippet:

![image](https://user-images.githubusercontent.com/22648831/231587706-e0c8a76c-ccbd-4808-bfdb-921a21a0fd62.png)

@isvargasmsft @sebastienlevert @CarolKigoonya can you take a look at the suggestion and add any other thoughts?

**Comment by isvargasmsft** [comment]
I agree with adding a small flag with the version just for clarification. That could also promote upgrading to newer versions of the SDK.

**Comment by lramosvea** [comment]
We do need to add the SDK version used to generate the snippets.

**Comment by sebastienlevert** [comment]
This should be part of the snippet so it would also work with Graph Explorer. I agree this would deliver clear expectations for developers.

**Comment by andrueastman** [comment]
For the docs, we could probably do something like this. If we place a note inside the snippet block we run into the issue where using the copy functionality results in the user copying invalid code that may not compile. 

[Update user - Microsoft Graph beta | Microsoft Learn](https://review.learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-21137&tabs=csharp#request)

![image](https://user-images.githubusercontent.com/6464005/235618686-4dcb1c64-c872-4b26-96e8-10a750584434.png)


The alternative is to use the option below with the text appearing as a code comment. This will also easily work with the Graph Explorer. 

[Update user - Microsoft Graph beta | Microsoft Learn](https://review.learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-21138&tabs=csharp#request)

![image](https://user-images.githubusercontent.com/6464005/235618552-7c882d01-10dc-4b14-b76b-4dde3653cac5.png)

**Comment by sebastienlevert** [comment]
I like this option as it easily spans across all properties where we show snippets!

**Comment by maisarissi** [comment]
If we choose to go with the first option, which looks way better in our docs than just a comment line, would Graph Explorer be able to follow a similar pattern?

**Comment by sebastienlevert** [comment]
Also, the fact that the version is copy / pasted is fairly interesting as it bring this context over to the developers IDE.

**Comment by maisarissi** [comment]
I agree with those points, however I feel that the code comment is "less visible", in a sense that, it's easier to ignore the information as opposed to the Note option that creates a block to draw the readers' attention to it.

What if we add the comment in the code snippet but in the docs we keep the Note as well?

**Comment by maisarissi** [comment]
Ok! So I'll summarize our agreement:

- Have a include file with "Code snippets are only available for the latest version. Current version is 5.x"
- Use the include file to generate the Note section in the docs
- Also have the comment in the code showing the version so we can have the same information in Graph Explorer (this will duplicate the information for people in docs, but I don't think this is a problem)

The final version would be:
![image](https://user-images.githubusercontent.com/22648831/235720666-49d210d1-1e65-42e5-bae3-beaaf0dafcf0.png)

@sebastienlevert @isvargasmsft @andrueastman

**Comment by lramosvea** [comment]
I like having the note although not sure if this will look good on docs where we have many notes already and this might be a bit overwhelming for users. Let me share this with Steve.

**Comment by maisarissi** [comment]
Hey @lramosvea have you checked with Steve? We believe this will bring clarity to users.

**Comment by lramosvea** [comment]
Can't tag Steve here but did share this with him. Let me follow up and I'll get back to you.

**Comment by ddyett** [comment]
@lramosvea awaiting word of decision.

**Comment by lramosvea** [comment]
@ddyett @maisarissi after discussing this with the rest of the docs team, our recommendation is to just keep the comment in the code. We don't think the note needs to be added,

**Comment by ddyett** [comment]
@ddyett to move to global backlog. .NET complete but needs tracking for other languages.

**Comment by andrueastman** [comment]
Closing this for now given the available spec. This has been broken down into individual language issues below
CLI - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1935
Go - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1936
Python - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1937
PHP - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1938
Typescript - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1939
Powershell - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1940
