### ISSUE TITLE
DevX API Reliability Issue

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1055]
**Describe the bug**
`500 out-of-memory` error when calling DevX API with `forceRefresh=true` when `graphVersion` is `beta` and intermittently in `v1.0`.

**To Reproduce**
1. Open https://graphexplorerapi.azurewebsites.net/openapi/operations?openapiversion=3&style=Powershell&graphVersion=beta&forceRefresh=true from your browser.
2. See error: `{"StatusCode":500,"Message":"Exception of type 'System.OutOfMemoryException' was thrown."}`

**Expected behavior**
An OpenAPI document should be returned when `forceRefresh=true`.

**Additional context**
The issue is blocking PowerShell's weekly OpenAPI refreshes from getting the latest API refreshes.

**Comment by irvinesunday** [comment]
According to App Insights telemetry, this is where the exception gets thrown: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/7114d5f9441d1a8f3edae59326a18b6b9e418749/OpenAPIService/OpenApiService.cs#L665. 
During fixing of references in the OpenAPI document, the document is first serialized into a `StringBuilder` [object](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/7114d5f9441d1a8f3edae59326a18b6b9e418749/OpenAPIService/OpenApiService.cs#L663). The conversion of the `StringBuilder` object to a string and the `OpenAPI.NET` library method that reads this string (`OpenApiStringReader().Read()`) ends up allocating a significant amount of memory for this process, especially for `beta` paths, which are appr. double the size of `v1.0` paths. There is need to review this fixing of references.

**Comment by irvinesunday** [comment]
This has been temporarily resolved by scaling up the DevX API app service plan to allocate more memory.
