### ISSUE TITLE
missing AddAsync

### ISSUE THREAD

**Issue by Michael-Grosser** [microsoftgraph/microsoft-graph-devx-api#1063]
[Hello, I can't find AddAsync (but PostAsync) if I use Beta Package. Pls. update this example. BR Michael]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 558e6675-990e-b571-6bfb-7392f097edbe
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Mitglieder hinzufügen - Microsoft Graph beta](https://docs.microsoft.com/de-de/graph/api/group-post-members?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs.de-DE/blob/main/api-reference/beta/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Resolved with V5 snippet generation
