### ISSUE TITLE
c# example doesn't work for list of deleted objects

### ISSUE THREAD

**Issue by k-krupka** [microsoftgraph/microsoft-graph-devx-api#1064]
As per title. I think the API changed along the way and not it does not support a generic query against the deleted Objects. You have to specify additional URL part, i.e. group, user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf76efc-5ca2-e829-1604-fa858179858a
* Version Independent ID: bbf2d629-8795-3d87-76de-f147489e4942
* Content: [List deletedItems (directory objects) - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directory-deleteditems-list.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zengin** [comment]
odata type casts are not supported in the current version of the SDK. This should be fixed in snippets generated for kiota based SDK.

**Comment by zengin** [comment]
Cast support was added in SDK v5 and snippets are updated to reflect that.
