### ISSUE TITLE
Slicing by tags using REGEX is broken.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1082]
**Describe the bug**
Slicing of OpenAPI documents by tags via REGEX is broken and fails with `{"StatusCode":404,"Message":"No paths found for the supplied parameters."}`.

Last successful run was on `07/13/2022`. 

**To Reproduce**
- https://graphexplorerapi.azurewebsites.net/$openapi?tags=^groups.group$&title=Groups&openapiversion=3&style=Powershell&graphVersion=v1.0
- https://graphexplorerapi.azurewebsites.net/$openapi?tags=^teams\.&title=Teams&openapiversion=3&style=Powershell&graphVersion=v1.0
- https://graphexplorerapi.azurewebsites.net/$openapi?tags=^security\.&title=Security&openapiversion=3&style=Powershell&graphVersion=v1.0

Fail with:
`{"StatusCode":404,"Message":"No paths found for the supplied parameters."}`

**Expected behavior**
A sliced OpenAPI document should be returned based on the provided REGEX in the tags query parameter.

PowerShell uses a REGEX based mapping to slicing Microsoft Graph APIs into modules. See https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/config/ModulesMapping.jsonc.

**Comment by irvinesunday** [comment]
This is the cause of the issue: (`Regex.Escape()`) https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/7bef128861238f324f3b738d14f803f151f41058/OpenAPIService/OpenApiService.cs#L186

**Comment by peombwa** [comment]
Reopening the issue as the problem is reoccurring again in the latest deployment. See https://graphexplorerapi.azurewebsites.net/$openapi?tags=^security.&title=Security&openapiversion=3&style=Powershell&graphVersion=v1.0.
