### ISSUE TITLE
Example 2: Add multiple members to a group in a single request C# not working 

### ISSUE THREAD

**Issue by hieudo989** [microsoftgraph/microsoft-graph-devx-api#1083]
Example 2: Add multiple members to a group in a single request
Has to use solution from https://stackoverflow.com/questions/62475635/add-users-as-group-members-with-microsoft-graph-api-in-net-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1006

Resolved with v5 snippet generation
