### ISSUE TITLE
Go snippets result variable inconsistent with other languages.

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-devx-api#1114]
**Describe the bug**
C#, Java, and JavaScript all define a result variable that has a name derived from the type. For example, the request in Graph Explorer:

```
GET https://graph.microsoft.com/v1.0/groups
```

Will result in a snippet like this in C#:

```csharp
var groups = await graphClient.Groups
	.Request()
	.GetAsync();
```

But in Go, it just uses a generic `result`.

```go
result, err := graphClient.Groups().Get()
```

**To Reproduce**
Look at the snippets on Graph Explorer for any GET request.

**Expected behavior**
Go snippets should be consistent with the other languages. I'd expect something like

```go
groups, err := graphClient.Groups().Get()
```

**Comment by rkodev** [comment]
@ddyett @jasonjoh It looks like all the other languages have now adopted the name `result` for the variable, can we close this ticket?

**Comment by jasonjoh** [comment]
I see C# has move to this, but Java and JavaScript still use the more descriptive name for the result variable.

IMO, we should use a more descriptive name and avoid the generic `result`.
