### ISSUE TITLE
Go snippets ID values inconsistent with other languages

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-devx-api#1115]
**Describe the bug**
C#, Java, and JavaScript all use the ID value from the source query. For example, the request in Graph Explorer:

```
GET https://graph.microsoft.com/v1.0/groups/04b7332d-836f-4083-ae1a-6a2e7cb1e251
```

Will result in a snippet like this in C#:

```csharp
var group = await graphClient.Groups["04b7332d-836f-4083-ae1a-6a2e7cb1e251"]
	.Request()
	.GetAsync();
```

But in Go, it just uses a generic `result`.

```go
result, err := graphClient.GroupsById("group-id").Get()
```

**To Reproduce**
Look at the snippets on Graph Explorer for any GET request.

**Expected behavior**
Go snippets should be consistent with the other languages. I'd expect something like

```go
groups, err := graphClient.Groups().Get("04b7332d-836f-4083-ae1a-6a2e7cb1e251")
```

**Comment by zengin** [comment]
This was introduced as a feature for the snippets in the docs. The ID formatting is not consistent in the HTTP snippets, so snippet generation logic resolves the ID type and replaces with a consistent placeholder {entityType-id}. It helps in Raptor execution tests to be able to replace with correct IDs from a test tenant.

When ID replacement was implemented for C#, I also introduced an "IsCommandLine" parameter to differentiate two snippet generation scenarios, but it looks like that feature is not propagated to the new languages that were added later on:

https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/389797e685b8acbea883d2db76e4991fca284040/CodeSnippetsReflection.OData/LanguageGenerators/CSharpGenerator.cs#L353-L376
