### ISSUE TITLE
Missing RequestBodies in `/$ref` paths

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1129]
**Describe the bug**
Request bodies are missing in `/$ref` paths.

**To Reproduce**
1. Go to https://graphexplorerapi.azurewebsites.net/$openapi?tags=groups.directoryObject&title=Users&openapiversion=3&style=Powershell&graphVersion=v1.0
2. Inspect `/groups/{group-id}/members/$ref` -> `Post` operation:
![image](https://user-images.githubusercontent.com/7061532/183119808-d6c9cb2f-1d92-4747-bc85-e6096a5c8abf.png)
You'll see that `requestBody` is missing in the operation.

**Expected behavior**
RequestBodies should be present in `/$ref` paths.
``` diff
'/groups/{group-id}/members/$ref':
  post:
    tags:
      - groups.directoryObject
    summary: Create new navigation property ref to members for groups
    operationId: groups_CreateMembersByRef
    parameters:
      - name: group-id
        in: path
        description: 'key: id of group'
        required: true
        schema:
          type: string
        x-ms-docs-key-type: group
+   requestBody:
+    $ref: '#/components/requestBodies/refPostBody'
    responses:
      '204':
        description: Success
      4XX:
        $ref: '#/components/responses/error'
      5XX:
        $ref: '#/components/responses/error'
    x-ms-docs-operation-type: operation
```

**Comment by peombwa** [comment]
I've managed to track down the issue to: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/515c781bdc04b60f01a69609b09f3d43c0550589/OpenAPIService/OpenApiService.cs#L621

Is there a reason why we need to clone a subset of an already [cloned OpenAPI document](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/OpenAPIService/OpenApiService.cs#L725)? Removing the clone method on the subset fixes the problem.

**Comment by ddyett** [comment]
@adhiambovivian @millicentachieng  can we expedite as it breaks all powershell.

**Comment by millicentachieng** [comment]
@ddyett Noted
