### ISSUE TITLE
Update CloneOpenApiDocument to use copyConstructors instead of writing and reading new document.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-devx-api#1145]
The current cloneOpenApiDocument is very inefficient.  The new copyConstructors in OpenApi.NET 1.4 should significantly improve the performance and reduce memory usage.  (Using copy constructors causes the clone to share the instances of the string. This means no new strings need to be created for the clone)  Related to #1142

**Comment by darrelmiller** [comment]
Blocked on the release of OpenApi.Net 1.4.0-preview3 that will contain this fix https://github.com/microsoft/OpenAPI.NET/issues/850

**Comment by MaggieKimani1** [comment]
Dependent on a fix for this https://github.com/microsoft/OpenAPI.NET/issues/995

**Comment by njaci1** [comment]
@MaggieKimani1 could you check with @irvinesunday  why copyConstructors is failing?

**Comment by millicentachieng** [comment]
Fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411 and https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/956. We are now reading the Open API document from the metadata repo and caching different copies of the Open API document for each style.
