### ISSUE TITLE
Applying styles is corrupting the source in-memory OpenAPI documents.

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-devx-api#1227]
I believe this PR https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1147/files is now modifying the source OpenAPI document and when people use AutoComplete in GE it will be deleting request/response bodies from the source OpenAPIDocument.  This will cause a problem for PowerShell because they will not get a complete OpenAPI document.

This issue is partially mitigated because we refresh the OpenAPIDocument every 15 mins, however, it still could cause a problem that would be hard to detect.

We need to either resolve the issue with getting copyConstructors working to clone the document, or we need to put the old cloning back in.  I think.

**Comment by irvinesunday** [comment]
Related to: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1145

**Comment by millicentachieng** [comment]
This was fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1180
