### ISSUE TITLE
Please add $select to `GET auditLogs/signIns`

### ISSUE THREAD

**Issue by joeldeteves** [microsoftgraph/microsoft-graph-devx-api#1250]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use `$select` with the auditLogs/signIns API. This leads to massive requests each time when attempting to pull the Sign In Logs through the REST API: https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=http

**Describe the solution you'd like**
- We would like to be able to select specific fields e.g. userPrincipalName, ipAddress, deviceDetail, etc as the current output for each log item is huge and filled with tons of unused fields. Currently it results in the following: `Query option 'Select' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.`

**Describe alternatives you've considered**
Right now I have to filter the data I want to select on my side. This is do-able but pulling the logs we need results in over 3MB of data - it's not efficient at all to have to fetch this each time.

**Additional context**

**Comment by RedwingBI** [comment]
I must echo joeldeteves. I have the same problem.  Any idea when this functionality is going to be present?

**Comment by millicentachieng** [comment]
Hi @joeldeteves,

Thank you for reporting your concern. Unfortunately, we do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
