### ISSUE TITLE
Remove NA from list of permissions appearing on GE under profile >consent to permissions

### ISSUE THREAD

**Issue by njaci1** [microsoftgraph/microsoft-graph-devx-api#1260]
If you go signed in user profile on GE, among the permissions listed for consent to permission is "NA". we agreed with @irvinesunday to filter this out on DevX API so that it will not appear on GE. This is linked to issue #1253

![Image](https://user-images.githubusercontent.com/43107183/203012826-3e03bb69-6fdd-4c01-9336-83be3909b3fa.png)

![Image](https://user-images.githubusercontent.com/43107183/203013134-3e7b5b0e-5175-4ee3-acda-a1e841ff9440.png)

**Comment by irvinesunday** [comment]
Closed with this PR: https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1264
