### ISSUE TITLE
Investigate intermittent permission information unavailability issue

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#1263]
When permission for a given endpoint is requested, the `consentDisplayName` and `consentDescription` information gets shown intermittently, example: https://graphexplorerapi.azurewebsites.net/permissions?requestUrl=/groups&method=GET

![image](https://user-images.githubusercontent.com/40403681/203987526-7fd4e6df-bd8b-4ad5-a030-eba6cf1ff7eb.png)
_information unavailable_

 vs

![image](https://user-images.githubusercontent.com/40403681/203987607-9ea9941c-0b44-4fb7-b0b4-9944f320bc52.png)
_information available_

We need to investigate why this happens and fix this.

One area where we can immediately try and plug a potential issue is in making sure that we use the supported locale variants when creating in-memory caches for permissions i.e., `en-US`, `de-DE`, `ja-JP`, `zh-CN`, `pt-BR`, `ru-RU`, `es-ES`, `fr-FR`. Currently we create caches for any locale variant that we get from a client, even though we serve the supported permissions. This means we create several caches of different variants with potentially the same localized permissions.

Related to https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2243

**Comment by irvinesunday** [comment]
Re-opening this issue as the issue still persists.

**Comment by irvinesunday** [comment]
The issue doesn't get repro'd in the staging endpoint however, https://graphexplorerapi-staging.azurewebsites.net/permissions?requestUrl=/groups&method=GET and neither when tested locally. Technically both staging and prod have the same permissions code, with the exception of some of the telemetry and exception code removed in prod. with this [PR](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1286)
Could this potentially be an infrastructure issue with prod.?

**Comment by zengin** [comment]
quick note: this doesn't seem limited to the localized fields, `isAdmin` is also fetched as default `false` value of the boolean type in the error case, even though the expected value is `true`.

**Comment by irvinesunday** [comment]
> quick note: this doesn't seem to be limited to the localized fields, `isAdmin` is also fetched as default `false` value of the boolean type in the error case, even though the expected value is `true`.

That's because all properties are set to their defaults when there is no scopes information data
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/a85d5cc01d0f8591d0712fce88106ba63be94689/PermissionsService/Models/ScopeInformation.cs#L14-L21

**Comment by zengin** [comment]
> > quick note: this doesn't seem to be limited to the localized fields, `isAdmin` is also fetched as default `false` value of the boolean type in the error case, even though the expected value is `true`.
> 
> That's because all properties are set to their defaults when there is no scopes information data
> 
> https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/a85d5cc01d0f8591d0712fce88106ba63be94689/PermissionsService/Models/ScopeInformation.cs#L14-L21

well, `ScopeName` (`value` in JSON) is not the default value `Scope name unavailable`, so there is something special about that.

**Comment by zengin** [comment]
relevant line which overrides the default `ScopeName` value even if the lookup fails:

https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/a85d5cc01d0f8591d0712fce88106ba63be94689/PermissionsService/Services/PermissionsStore.cs#L500

**Comment by zengin** [comment]
The fact that the entries are generated by the line 500 mentioned above is consistent with the telemetry produced from the following code block:

https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/a85d5cc01d0f8591d0712fce88106ba63be94689/PermissionsService/Services/PermissionsStore.cs#L488-L496

Telemetry:
---

![image](https://user-images.githubusercontent.com/803311/209005144-ee5c19f5-4044-4be8-8d2b-76fe173bbee5.png)

---

What's surprising is that outer dictionary has the entry e.g. [Delegated], but not the entries inside that dictionary. There is no explicit step which would update the inner dictionary independently, so that gives me doubt that this is a race condition in caching. Updates to the cache at the higher level, i.e. for cache key: `ScopesInfoList_en-US`, looks atomic due to the lock, even though single entry into the factory is not guaranteed by the MemoryCache implementation.

https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/a85d5cc01d0f8591d0712fce88106ba63be94689/PermissionsService/Services/PermissionsStore.cs#L183-L229

**Comment by zengin** [comment]
We also have this telemetry which explains empty inner dictionary and all the downstream behavior, but doesn't tell us why it is 0 entry in the first place:

![image](https://user-images.githubusercontent.com/803311/209008548-bfa9e3fc-55ea-4e12-9cab-33dfe6cfe903.png)

**Comment by zengin** [comment]
Additional telemetry reveals that scopes information tables are not populated in some cases:

![image](https://user-images.githubusercontent.com/803311/213327064-04bc5b7a-e577-4adf-b64a-7fb3e3fcedd1.png)

We might be relying on a cache that doesn't hold any elements in it.

**Comment by zengin** [comment]
Contents of the file is not the scopesInfo (descriptions), but rather the version specific permissions:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/803311/213329470-823915ec-02b3-4b5e-bec4-bfdaf9a2ac95.png)

It looks like there might be a bug in file name picker logic.

**Comment by zengin** [comment]
Scopes info fetching permissions, not the permission descriptions:

![image](https://user-images.githubusercontent.com/803311/213347060-a24f961e-6b17-43e0-9811-5eb7b3c28bf5.png)
