### ISSUE TITLE
Path parameters are missing from parameters object

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1280]
**Describe the bug**
Path parameters are missing from parameters object in the resultant OpenAPI document.

**To Reproduce**
1. Go to [`applications.application.GetApplication` operation id](https://graphexplorerapi.azurewebsites.net/openapi?operationIds=applications.application.GetApplication&openApiVersion=3&graphVersion=v1.0&format=yaml&style=PowerShell).
2. Inspect parameters object/path item.
3. See missing path parameters, application-id in this case:
![image](https://user-images.githubusercontent.com/7061532/206318950-eaffe583-eaa3-43a0-b1b7-f88790073f01.png)

**Expected behavior**
Path parameters should be defined in the parameters object.

**Screenshots**
See steps to reproduce above.

**Comment by irvinesunday** [comment]
`DeclarePathParametersOnPathItem` needed to be set to `false` in the app service configuration. 
@peombwa kindly confirm this is now working as expected.

**Comment by peombwa** [comment]
Thanks for the fix!

Everything works as expected. I'll close the issue.
