### ISSUE TITLE
Wrong parameter for cmdlet 

### ISSUE THREAD

**Issue by SabRom** [microsoftgraph/microsoft-graph-devx-api#1282]
Hello,

In example 2, powershell request mention : 

Get-MgUserMailFolder -UserId $userId **-Includehiddenfolders true** 

It does not seem like -IncludeHiddenfolders is a valid parameter for Get-MgUserMailFolder cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad44cdb-5d58-2689-6731-f9b1f791c33f
* Version Independent ID: 5f41b59d-994a-36d8-978f-db8a738fe10d
* Content: [List mailFolders - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
cc @msewaweru for visibility.

**Comment by zengin** [comment]
cc: @timayabi2020 @peombwa

**Comment by timayabi2020** [comment]
@SabRom The example was updated and we no longer have -Includehiddenfolders query parameter. See [reference](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.mail/get-mgusermailfolder?view=graph-powershell-1.0)

**Comment by peombwa** [comment]
The query parameter was missing in the metadata. The parameter was added to the metadata by https://github.com/microsoftgraph/msgraph-metadata/pull/319.

The command should now support the query parameter as of v1.27.0.

**Comment by peombwa** [comment]
![image](https://user-images.githubusercontent.com/7061532/235783010-056506d3-d8ed-46ab-9b50-8f89beecf7db.png)
