### ISSUE TITLE
PowerShell from "Example 1" returns a "The request is invalid" error

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-devx-api#1297]
When I run the PowerShell from "Example 1", I get a "The request is invalid" error.

I can run it successfully if I change the "Query" and "QueryType" properties from "Scope" to "query" and "queryType". (there might be other solutions without changing the properties' casing)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9f57e3-04f9-8e00-efc5-e7b0bd6ebf6c
* Version Independent ID: 4bbaa69b-d41e-6290-acdb-35eb06ffb9d3
* Content: [Create definitions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&tabs=powershell)
* Content Source: [api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewset-post-definitions.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @isabelleatmsft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by millicentachieng** [comment]
Please refer to this [comment](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1628#issuecomment-1315889298).
