### ISSUE TITLE
PowerShell Examples Are Incorrect

### ISSUE THREAD

**Issue by rednender** [microsoftgraph/microsoft-graph-devx-api#1328]
Get-MGGroupDelta does not have a SkipToken or DeltaToken property as shown in the examples.  Verified in verssion 1.13.0, 1.20.0 and 2.0.0-Preview4.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdaf58ca-8b6c-cddd-f583-f8617b0450a6
* Version Independent ID: 08b26245-df55-d5d5-a6d2-edc69eda3fe3
* Content: [Get incremental changes for groups - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-groups?tabs=http)
* Content Source: [concepts/delta-query-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ddyett** [comment]
closing older issue. We will address this issue through our validation system to clean up the examples.
