### ISSUE TITLE
How do we do this using Graph Powershell module?

### ISSUE THREAD

**Issue by jonwbstr** [microsoftgraph/microsoft-graph-devx-api#1331]
The powershell example provided, is using a deprecated module. I believe the preferred approach is
1) partner installs graph powershell module
2) partner creates application to manage customer tenants using graph powershell module
3) partner connects to customer tenant using graph powershell module

I believe we can use the ```New-MgApplication``` command to create the application in the partner tenant, yes?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8f7169c-463e-61c1-dfe1-38a43f4d696b
* Version Independent ID: a27fdad3-5138-6cd5-cb17-30be944dfb25
* Content: [Call Microsoft Graph from a Cloud Solution Provider application - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-cloudsolutionprovider?tabs=azuread)
* Content Source: [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-cloudsolutionprovider.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jonwbstr** [comment]
The article this was opened against has gone through some changes. The article currently describes how to add the partner app to the admin agents group but there is a caviant:

> Calling Microsoft Graph from a CSP application is only supported for directory resources (such as user, group,device, organization) and [Intune](https://learn.microsoft.com/en-us/graph/api/resources/intune-graph-overview) resources.

Still wrapping my head around the implications of all these upcoming changes.

**Comment by ddyett** [comment]
closing out an older issue but we have been working on addressing any incorrect snippets. please re-open issue if this case is a problem.
