### ISSUE TITLE
Missing `x-ms-navigationProperty: true` on single-valued navigation properties after OData to Open API conversion

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-devx-api#1348]
**Describe the bug**
This is only affecting the PowerShell style since after applying the `AnyOfRemover`, sibling properties of the reference object are ignored.

Output without applying the `AnyOfRemover`:
```yaml
team:
    anyOf:
        - $ref: "#/components/schemas/microsoft.graph.team"
        - type: object
          nullable: true
    description: The team associated with this group.
    x-ms-navigationProperty: true
```
Output after applying the `AnyOfRemover`:
```yaml
team:
    $ref: "#/components/schemas/microsoft.graph.team"
```
Updating the `AnyOfRemover` to produce the below output was suggested but that still won't work for AutoRest.
```yaml
team:
     allOf:
          - $ref: "#/components/schemas/microsoft.graph.team"
          - type: object
            description: The team associated with this group.
            x-ms-navigationProperty: true
```

**Expected behavior**
Find a schema representation that will include the ` x-ms-navigationProperty:` extension and still work for AutoRest.

**Comment by millicentachieng** [comment]
@peombwa Do you mind tagging the AutoRest issue here once you create it?

**Comment by peombwa** [comment]
Here is the AutoREST.PowerShell tracking issue -https://github.com/Azure/autorest.powershell/issues/1105.

We can go ahead and implement the change in DevX API once they've acknowledged the issue as a bug.

**Comment by peombwa** [comment]
@millicentachieng, can we represent the navigation property as such?
``` yml
properties:
  team:
    allOf:
      - $ref: '#/components/schemas/microsoft.graph.team'
      - type: object
        description: The team associated with this group.
    x-ms-navigationProperty: true
```
Effectively replacing the `anyOf` with `allOf`.

The above representation is supported by AutoREST, and will fix the issue for us.

**Comment by millicentachieng** [comment]
@peombwa. I've created this [PR](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1359) to make the translation.
