### ISSUE TITLE
Snippets generation accidentally deleted blocks of content and examples

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#1357]
**Describe the bug**
We and our partners are finding cases of content that was accidentally deleted during the snippets autogeneration process.

Currently, we've discovered the issue against some conceptual articles (articles located in the [microsoft-graph-docs/concepts/](https://github.com/microsoftgraph/microsoft-graph-docs/tree/main/concepts) folder). I don't know if any reference articles are affected.

For example, in this article [Use privileged identity management (PIM) to update Azure AD rules - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/how-to-pim-update-rules?view=graph-rest-1.0&tabs=http&source=docs) examples 2-5 were deleted through the following commits.

- This snippets generation [Update generated files with build 99731 · microsoftgraph/microsoft-graph-docs@4f2becf (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/commit/4f2becf8eebd1d2b60732195534cc5a591a47e8c#diff-4ca8caa148322623604dade686fc5aae15f98e32b454d4ac96920074f050c5c8) deleted Example 2
- This snippets generation [Update generated files with build 100783 · microsoftgraph/microsoft-graph-docs@07d9c96 (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/commit/07d9c965be06aa3d15fe51385018fab12b0f12c1#diff-4ca8caa148322623604dade686fc5aae15f98e32b454d4ac96920074f050c5c8) deleted Example 3
- This snippets generation [Update generated files with build 102229 · microsoftgraph/microsoft-graph-docs@1608b27 (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/commit/1608b27da715ece43e3499977f89ffa2a86d10b8#diff-4ca8caa148322623604dade686fc5aae15f98e32b454d4ac96920074f050c5c8) deleted Example 4
- This snippets generation [Update generated files with build 103120 · microsoftgraph/microsoft-graph-docs@d19604e (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/commit/d19604e4025a1750608048d30d3e9a10adc855ef#diff-4ca8caa148322623604dade686fc5aae15f98e32b454d4ac96920074f050c5c8) deleted Example 5

I manually restored the examples through this commit [Restore accidentally deleted examples](https://github.com/microsoftgraph/microsoft-graph-docs/commit/c05032db8985ca6c8a71b37c0bcff6351274cc05), but a few days later, the snippets generator now deleted six examples via this commit  https://github.com/microsoftgraph/microsoft-graph-docs/commit/bc81be1f30a7b9af336fb37a6e4b3d376f829adb😭!

Also:
+ For this article [Use the $search query parameter](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http), two pages worth of scrolling length were accidentally deleted via this commit https://github.com/microsoftgraph/microsoft-graph-docs/commit/4f2becf8eebd1d2b60732195534cc5a591a47e8c#diff-c0109aa279bb51917fecc32cd9af1089b4e63c11c8a88cd7373bdbda6f76e55c
+ For this article [Manage an Azure AD application using Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorial-applications-basics?tabs=http%2Ccsharp), one example was deleted via this commit https://github.com/microsoftgraph/microsoft-graph-docs/commit/4f2becf8eebd1d2b60732195534cc5a591a47e8c#diff-c0109aa279bb51917fecc32cd9af1089b4e63c11c8a88cd7373bdbda6f76e55c

**Expected behavior**
The snippets generator should only add/remove code snippets and the respective H1 tabs.

**Screenshots**
<img width="881" alt="image" src="https://user-images.githubusercontent.com/14026935/217179348-951d3468-41a8-4e2b-90b9-f94512e39a9c.png">

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/14026935/217179532-d6f8c79a-c445-4a42-9d81-96eedd323fbc.png">

cc @andrueastman to help resolve
cc @lauragra for visibility

**Comment by andrueastman** [comment]
Hey @FaithOmbongi, 

Thanks for raising this. We'll track this via https://github.com/OneDrive/apidoctor/issues/177 as this has now been confirmed to be an APIDoctor issue.
