### ISSUE TITLE
[Feature] Update `operationId`s for `PowerShell` style

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#1408]
Currently, PowerShell v2 generates cmdlet names that are not aligned to the cmdlet names generated by v1. This is an AutoREST v3 issue that is being followed up in their channels. We need an interim solution that can resolve this for PowerShell cmdlet generation. A detailed issue description of this issue is given [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1788).
The proposal is to correct this in the DevX API when generating subset OpenAPI documents for PowerShell style.

Below is a proposal on how to resolve this in the DevX API, when styling for PowerShell:

Given an operationId: `identityGovernance.lifecycleWorkflows.workflows.workflow.activate`
The operationId will be split on each segment, discarding the last segment: 
1. identityGovernance
2. lifecycleWorkflows
3. workflows
4. workflow

Each segment will be de-pluralized:
1. identityGovernance
2. lifecycleWorkflow
3. workflow
4. workflow

Starting from the last segment going upwards, check whether this value is a substring of another segment, if `true` remove it.
1. identityGovernance
2. lifecycleWorkflow

In the above scenario, **workflow** (4th segment) is a substring on the 3rd segment and **workflow** (3rd segment) is a substring on the 2nd segment, **lifecycleWorkflow**.

Now stitch back together the remaining segments and append the last segment that was previously discarded -> `identityGovernance.lifecycleWorkflow.activate`
The PowerShell operationId styling guideline will then prefix a `_` before the last segment -> `identityGovernance.lifecycleWorkflow_activate`
The PowerShell cmdlet that will be generated from the above will be: `Initialize-MgIdentityGovernanceLifecycleWorkflow`

**Comment by timayabi2020** [comment]
This approach looks feasible for such scenarios, we can try it out on devx test and locally run the resultant open api files against both Autorest versions i.e., V2 and V3. This way, we will know if the previously affected cmdlets generated by autorest v3 will be singularized on both autorest v1 and v2.
