### ISSUE TITLE
 Use an InMemoryCache instead of implementing locking/caching

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-devx-api#1420]
**Is your feature request related to a problem? Please describe.**
This comes from [this comment](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411#discussion_r1129456362) on [Feature: change open api gen process](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411)

>Just use an InMemoryCache and use the [GetOrCreateAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.getorcreateasync?view=dotnet-plat-ext-7.0) method.
It's thread safe because designed for aspnet scenarios.
We could even imagine using a background service populating the cache so requests don't hang.
https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-7.0

**Describe the solution you'd like**
We should not do the caching and locking ourselves and should depend on the in Memory Cache

**Comment by millicentachieng** [comment]
Closing in favor of #1456
