### ISSUE TITLE
Change http consumption patterns

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-devx-api#1421]
**Is your feature request related to a problem? Please describe.**
This comes from [this comment](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411#discussion_r1129464071) on [Feature: change open api gen process](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411)

>Instantiating http client randomly without disposing them WILL lead to port exhaustion.
Please have the constructor accept and set as a field an IHttpClientFactory instead and configure the dependency injection to setup the client for you.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0

**Describe the solution you'd like**
We should make use of dependency injection for the http clients used in the application

**Comment by baywet** [comment]
Additionally we should avoid locking things (even async) and use the [infrastructure asp.net provides instead](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1411/files#r1129456362)

**Comment by millicentachieng** [comment]
Closing in favor of #1445
