### ISSUE TITLE
Add Layering support for OpenAPI documents

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoftgraph/microsoft-graph-devx-api#1435]
**Feature description:**
Currently, DevX API has been encountering performance bottlenecks within the API's capacity as a result of growth of Graph resources and the size of the OpenAPI file over time. In a bid to optimize performance and memory usage while adding support for different sovereign clouds, a new proposal targeting layering of OpenAPI documents was born.
Using this layering approach should also help optimize external reference resolution.

**Possible solution:**
Using a layering approach when dealing with different versions of OpenAPI documents e.g. v1-fairfax.yaml and beta-fairfax.yaml
To layer two OpenAPI documents, you can merge the content of both documents into a single OpenAPI document.

**Example:** 

1. First document (petStore1.yaml)

```yaml
openapi: 3.0.0
info:
  title: Document 1
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Get all pets
      responses:
        200:
          description: Success
```

2. Second document (petStore2.yaml)

```yaml
openapi: 3.0.0
info:
  title: Document 2
  version: 1.0.0
paths:
  /pets/{id}:
    get:
      summary: Get a pet's details
      responses:
        200:
          description: Success
```

 3. Combined document

```yaml
openapi: 3.0.0
info:
  title: Combined Document
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Get all pets
      responses:
        200:
          description: Success
  /pets/{id}:
    get:
      summary: Get a pet's details
      responses:
        200:
          description: Success
```
**Additional Context:**
There are two possible approaches we're considering:

1. Using a collection that dedupes objects and shares memory between document object model graphs. We will however need to handle conflicts that may occur when both documents define the same elements (e.g., the same paths or properties) by removing the duplicate elements appearing in both documents. E.g.:
```c#
// merge 2 documents
petStore1.Attach(petStore2);

// Get DOM of the merged documents
var mergedInfo = petStore1.Info;
```

2. Adding a layer property to the object models which in memory will be represented as a collection e.g. a dictionary of type `<string, OpenAPIElement>`  which can help us index into a particular document and its properties e.g.

```c#
// Get DOM of a specific layer
var petStore1Info = petStore1.Layer["petStore1"].Info;
var petStore2Info = petStore1.Layer["petStore2"].Info;

```

Link to ongoing discussion: [https://github.com/microsoft/OpenAPI.NET/issues/1160#issuecomment-1426251183](url)
Cc: @baywet, @darrelmiller 
**FYI**: Bringing this conversation/issue over to DevX API as we're looking to have it implemented here as [per this comment](https://github.com/microsoft/OpenAPI.NET/issues/1160#issuecomment-1458275468).

**Comment by baywet** [comment]
Thanks for bringing this up. I think [my previous comment](https://github.com/microsoft/OpenAPI.NET/issues/1160#issuecomment-1426251183) laid out a couple of questions we should answer, in additional to designing the consumer experience, before thinking about solutions here.

That being said. I believe that if the layering were to be implemented in this library, it'd be interesting to get the layering aspect "abstracted away" from the consumer (except for the "I want to load all those layers" and "I want to write to this specific layer" aspects). This way we can implement the set of deterministic rules my questions were hinting at and facilitate the work for the consumer.

**Comment by millicentachieng** [comment]
We decided not to use layering but to use different Open API documents for each cloud.
