### ISSUE TITLE
Missing AddAsync Method for Administrative Unit Members

### ISSUE THREAD

**Issue by johnayoub** [microsoftgraph/microsoft-graph-devx-api#1451]
The following is the sample code provided in the docs. However, the AddAsync method is not available. I'm using version 4.54.0 of the SDK. Please advise.

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var directoryObject = new Group
{
	Description = "Self help community for golf",
	DisplayName = "Golf Assist",
	GroupTypes = new List<String>()
	{
		"Unified"
	},
	MailEnabled = true,
	MailNickname = "golfassist",
	SecurityEnabled = false
};

await graphClient.Directory.AdministrativeUnits["{administrativeUnit-id}"].Members
	.Request()
	.AddAsync(directoryObject);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da5a264-1674-dc75-0fc9-9af6ce2d7f8a
* Version Independent ID: ed0f3e90-2388-aaf8-9a1c-6274826ec56e
* Content: [Add a member - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=http#example-2-create-a-new-group)
* Content Source: [api-reference/v1.0/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/administrativeunit-post-members.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by johnayoub** [comment]
@jasonjoh Any update?

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-metadata/pull/368
Related to https://github.com/microsoftgraph/msgraph-metadata/issues/323
