### ISSUE TITLE
Add support for odata TypeSegment in the generator

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-devx-api#146]
Looking at this snippet found [here](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=csharp#request)

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var microsoft.graph.room = await graphClient.Places.Microsoft.graph.room
	.Request()
	.GetAsync();
```

There exists the section `Microsoft.graph.room` which is created due to the Odata TypeSegment `microsoft.graph.room` present in the url which is not currently supported by the generator. 
The SDK also does not seem to provide a fluent way to navigate into TypeSegments.

This needs to be investigated. 
We could possibly just use a version of creating customRequests to generate the snippet if there is really no way to navigate into TypeSegments.

Also related to the snippet at
https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=csharp#example 
[AB#7009](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7009)

**Comment by MIchaelMainer** [comment]
There is a way to [append a segment to the URL](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L324). If a segment as defined in the docs isn't described by the metadata, we may want to generate the use of the `AppendSegmentToRequestUrl` method to update the *Request. Too bad this isn't a request builder.

**Comment by darrelmiller** [comment]
@MIchaelMainer If this method returned a Request it would be much easier to use.  Currently you have to return the request, call this method on the request, and then call the operation.  Maybe we could make an overload called AppendSegment() that returns the request.

**Comment by zengin** [comment]
This is fixed with SDK v5.
