### ISSUE TITLE
[Snippet Generation] Stale C# v4 snippets are in the docs

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#1477]
**Describe the bug**
Snippet generation process doesn't remove existing snippet if it fails to generate a new one. When we moved from v4 to v5, some of the snippet generation failures meant that the docs ended up with stale v4 snippets.

e.g. https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-beta&tabs=csharp

**Expected behavior**
Snippet generation process should remove the snippet files that it can't generate for that particular run.

**Comment by andrueastman** [comment]
Resolved with https://github.com/OneDrive/apidoctor/pull/197. 

Will close once weekly generation runs tomorrow and docs update published.

**Comment by andrueastman** [comment]
Will close this one for now after the docs update at https://github.com/microsoftgraph/microsoft-graph-docs/pull/20976
