### ISSUE TITLE
[PowerShell] $count operationIds have a hash suffix in them

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1478]
`$count` `operationId`s have a hash suffix. This will lead to us generating command names with the hash in them. For example, `applications.appManagementPolicies_GetCount-3aad` will result in a command named `Get-MgBetaApplicationAppManagementPolicyCount3Aad`.

**Comment by irvinesunday** [comment]
@peombwa  should we just remove the suffix altogether from the conversion lib?

**Comment by peombwa** [comment]
Yes, that would be the ideal option. I already opened an issue in the conversion for us to look into this - https://github.com/microsoft/OpenAPI.NET.OData/issues/361.

**Comment by peombwa** [comment]
Fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1480.
