### ISSUE TITLE
Missing Open API Paths (Workbook and worksheets)

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/microsoft-graph-devx-api#1483]
The converted open Api document is missing paths related to workbook and worksheets for both v1.0 and beta. [This](https://learn.microsoft.com/en-us/graph/api/worksheet-get?view=graph-rest-1.0&tabs=http) is an example of a missing path. 
The bulk of failures reported during PowerShell snippet generation is associated with this issue

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/10947120/231172761-a0631510-ccd8-4afa-99bf-fdc53c9bc7ee.png">

**Comment by timayabi2020** [comment]
Closing this issue because of possible timeouts related to expansion of workbook navigation property

**Comment by millicentachieng** [comment]
> Closing this issue because of possible timeouts related to expansion of workbook navigation property

Closing...
