### ISSUE TITLE
Missing OpenAPI Path: /me/mailboxSettings

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/microsoft-graph-devx-api#1484]
The converted OpenApi document is missing /me/mailboxSettings. See [api reference](https://learn.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=http)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-metadata/pull/324
