### ISSUE TITLE
Delta functions only showing JavaScript sample

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/microsoft-graph-devx-api#1499]
We should investigate why delta functions are not showing code snippets other than JavaScript.
Example: https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http#response

**Comment by andrueastman** [comment]
This is a http tab issue. There should be no empty line between the request line and the Header list. The empty line should be between the headers and the request body and thus the header is "trying" to be parsed as a request body blocking snippet generation. https://github.com/microsoftgraph/microsoft-graph-docs/pull/20920

**Comment by andrueastman** [comment]
Snippet updated at https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http#response
