### ISSUE TITLE
Go Snippet Generation needs to reflect breaking change UsersById -> ByUserId

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#1513]
**Describe the bug**
SDK change: https://github.com/microsoftgraph/msgraph-sdk-go/pull/471/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

![image](https://user-images.githubusercontent.com/803311/233144992-74e851a8-cfec-4fbe-aa26-12e7eb9cf8cf.png)

**Expected behavior**
100% pass rate in stable compilation tests.

**Comment by rkodev** [comment]
Resloved by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1502
