### ISSUE TITLE
E-Discovery - EXPORT API Documentation Missing PowerShell

### ISSUE THREAD

**Issue by vbhatt0211** [microsoftgraph/microsoft-graph-devx-api#1516]
Hi Team, 

i had published documentation around export api resource under beta release. However, I dont see any PowerShell command reference for request mentioned.
Here is the link to documentation - https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewset-export?view=graph-rest-beta&tabs=http
PR link - https://github.com/microsoftgraph/microsoft-graph-docs/pull/20061
![MicrosoftTeams-image](https://user-images.githubusercontent.com/123445466/234046004-fcc59e8f-6b1c-41ea-8b02-3cec9d5e960c.png)

Please help in adding the wrapper class for the powershell command on the documentation

**Comment by vbhatt0211** [comment]
Any update on this?

**Comment by peombwa** [comment]
Closing as resolved. PowerShell snippets are now available on the API reference doc - https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewset-export?view=graph-rest-beta&tabs=powershell.

**Comment by millicentachieng** [comment]
Resolved.
