### ISSUE TITLE
Verify how many requests URLs the permissions endpoint can process at a time

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-devx-api#1531]
Do we need to have a cap?

**Comment by ElinorW** [comment]
Hey @millicentachieng , 
this may help you out: https://learn.microsoft.com/en-us/graph/permissions-overview?view=graph-rest-1.0&tabs=http#limits-on-requested-permissions-per-app

**Comment by millicentachieng** [comment]
Thanks @ElinorW

**Comment by millicentachieng** [comment]
We will cap at 400 since this is the maximum Microsoft Graph permissions an app can request.
