### ISSUE TITLE
[Snippets Generation] Stale PowerShell Snippet

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1551]
**Describe the bug**
Stale PowerShell snippet for the HTTP snippet at https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=powershell#request. `Revoke-MgUserSign` was renamed to `Revoke-MgUserSignInSession` a few versions ago.

Interestingly, the PowerShell snippets from Graph Explorer shows the correct command name:
![image](https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/7061532/572d71df-330b-43b2-a964-0c71b09b64cf)

**Expected behavior**
Language snippets in the API reference should all be updated in the same cadence as the SDKs.

**Comment by millicentachieng** [comment]
The snippet has been updated in the docs.
