### ISSUE TITLE
[Snippet Generation] Inconsistency in snippet generation when creating a Graph client

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/microsoft-graph-devx-api#1577]
In the API reference documentation, depending on the language you are looking at, we have different initialization of the client.
For example, looking at [List user](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp#request), C# and PHP initialize graph client with "request adapter", Java and JavaScript with authProvider and Go with token credentials.

I received question from folks trying to understand what is request adapter and believe this is causing unnecessary confusion.

We should have consistency among languages and would vote for token credential approach.

Would love to hear from others @isvargasmsft @sebastienlevert @CarolKigoonya

**Comment by sebastienlevert** [comment]
Is the link shared the right one you wanted to share? I see a link to Kiota?

**Comment by isvargasmsft** [comment]
https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http

I believe this is the right link. I see your point, Maisa, great catch. This is the type of issues that profoundly affect onboarding.

**Comment by sebastienlevert** [comment]
I agree we should have a unique way to drive how we think about auth. I believe the easiest way would be via a Credential. This simplifies a lot of what we do. So it's at the snippet that we generate this adapter... Is it really "required" or this should be an include outside the snippet? If I already have my app running, I probably don't need that and the copy feature now copies more than what I need...

**Comment by isvargasmsft** [comment]
I believe the snippet should only have the includes/import/use (depending on the language) and the code to call the method. I don't believe we should include initialization stuff in the snippet. Details about initialization should go in other articles.

**Comment by isvargasmsft** [comment]
PHP, Python and I believe JavaScript also need to specify the imports, otherwise the code wont work and devs will have to browse the service library manually to find the right path, assuming they know what they need. Not adding the imports to the snippet is just a frustrating experience.

I like the idea of adding a note to redirect people to introductory articles if they need to initialize.

**Comment by maisarissi** [comment]
These inconsistencies are being addressed by @sebastienlevert spec on snippet generation. The doc covers how snippets should look like.

**Comment by darrelmiller** [comment]
How can we make these snippets fit naturally into our ServiceAdapter class best practice and where should we provide that best practice guidance, and who is going to write it? :-)

**Comment by sebastienlevert** [comment]
I understand where you are coming for @darrelmiller but this is another concern IMO. I'm OK with revisiting these snippets if required when we get that best practice out. I feel the snippets should be as atomic as possible so the switch to the service adapter class should be transparent or minimal.

**Comment by andrueastman** [comment]
Closing this for now given the available spec. This has been broken down into individual language issues below
CLI - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1935
Go - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1936
Python - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1937
PHP - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1938
Typescript - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1939
Powershell - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1940
