### ISSUE TITLE
Include a check at the PR level to make sure example requests have unique names.

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/microsoft-graph-devx-api#1614]
Examples in documentation should have a unique name as stated in the documentation guidelines. However, today there is no mechanism preventing authors to overlook this and duplicate example names, which affects snippet generation process. 

We should add a test to catch these duplicate names at the docs PR level and fix them before they are published in the documentation.

**Comment by millicentachieng** [comment]
This has been enforced in the docs validation pipelines with the latest version of API Doctor.
