### ISSUE TITLE
Include a check to API Doctor to make sure all response examples have the odatatype

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/microsoft-graph-devx-api#1616]
Response examples in method topics should have the appropriate odatatype property defined where applicable. We can add a check on API Doctor to check this at the docs PR level.

**Comment by millicentachieng** [comment]
@isvargasmsft Please provide examples for the scenarios we are to target.

**Comment by isvargasmsft** [comment]
Hi Faith, I believe we can close this item by now. We want to focus first on the request examples that affect snippet generation. We'll leave the responses for later. It's ok to close this one for now.
