### ISSUE TITLE
Use the Namespace line to validate enums-{subnamespace}.md file instead of the namespace annotation at the bottom of the file

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#1638]
**Is your feature request related to a problem? Please describe.**
Today, API Doctor fails validation if the following annotation isn't added at the bottom of an enums.md file.

<img width="655" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/14026935/3a387a38-43fd-4678-831a-0fb207b7fce3">

**Describe the solution you'd like**
Every API reference doc already has a namespace line. It's a requirement. For enums.md files, including those in sub-namespaces, we have something like this 

<img width="584" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/14026935/99569c02-9106-4680-9a4b-87d1f4310ebd">

https://learn.microsoft.com/en-us/graph/api/resources/enums-identitygovernance?view=graph-rest-1.0

Requiring both this line and the namespace annotation at the bottom of the page is redundant.

Also, the base enums.md file for enumerations in the microsoft.graph namespace doesn't have or require this annotation.

Let's use the first namespace line at the top of the page instead.

**Comment by millicentachieng** [comment]
The return on investment for implementing this may not be justified considering that only enum files for new namespaces require the annotations.
