### ISSUE TITLE
API Doctor doesn't understand odata casting in the URL

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/microsoft-graph-devx-api#1665]
Sometimes API Producers will use odata casts in the HTTP URL. For example: 

POST /sites/{site-id}/pages/{page-id}/**microsoft.graph.sitePage**/canvasLayout/verticalSection

This is valid but API Doctor fails saying that “microsoft.graph.{resource}” is not a defined navigation property. 

We had this issue in PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/20977/files

To unblock the author and publish we changes to blocktype: ignored temporarily, but we need to fix this in API Doctor so we can properly generate snippets for these examples.

**Comment by isvargasmsft** [comment]
@millicentachieng

**Comment by millicentachieng** [comment]
Could you kindly consider adding suppressions to bypass the error? Unless we encounter additional instances of this issue, we will not prioritize addressing it at this time.
