### ISSUE TITLE
Correctly validate cross-repo references

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#1667]
_The issue was [originally filed in the API Doctor repo](https://github.com/OneDrive/apidoctor/issues/173) but opening a fresh one here for better visibility._

**Describe the bug**
API Doctor currently flags cross-repo references (CRRs) as broken links. However, the [Learn platform supports cross-repo reference which in essence is referencing an include file from one Learn repo by an article in another Learn repo](https://review.learn.microsoft.com/en-us/help/platform/includes-best-practices?toc=%2Fhelp%2Fplatform%2Ftoc.json&bc=%2Fhelp%2Fplatform%2Fbreadcrumb%2Ftoc.json&branch=main#cross-repo-includes).

API Doctor currently throws a "Link Definition was null" error when CRRs are encountered.

<img width="618" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/14026935/e94348ca-412e-488a-927f-fa716931d1a7">

The current false negative is a blocker for content reuse and reduction of duplicated content which is a key OKR for the Skilling org.

**To Reproduce**
You can see sample usage of cross-repo reference in this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/20284 and check the API Doctor output.

**Expected behavior**
The Learn platform understands CRRs. It's important that API Doctor also passes validation to unblock the Graph repo.

**Comment by FaithOmbongi** [comment]
cc @mwongerapk

**Comment by millicentachieng** [comment]
@FaithOmbongi The errors can be suppressed for the time being.

**Comment by FaithOmbongi** [comment]
@millicentachieng - I've added suppressions to this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/20284 unblock the use of CRR. We can revisit the permanent solution when you have bandwidth.

**Comment by millicentachieng** [comment]
@FaithOmbongi We are still waiting for a new API Doctor NuGet package with the updates to be published. This can take more than a month at times. The validation pipeline will be updated to use the new package once it's available.

**Comment by millicentachieng** [comment]
The validation pipeline was updated to use the newly created NuGet package. The suppressions can now be removed. Unused suppressions that are safe to remove can be seen at the bottom of the API Doctor validation log.

**Comment by FaithOmbongi** [comment]
> The validation pipeline was updated to use the newly created NuGet package. The suppressions can now be removed. Unused suppressions that are safe to remove can be seen at the bottom of the API Doctor validation log.

YAY! Confirmed as resolved. Thank you @millicentachieng and @andrueastman.

Here's the PR I've refreshed https://github.com/microsoftgraph/microsoft-graph-docs/pull/23049, and it's passed API Doctor validation. I also see messages for the unused suppressions - I'll proceed to remove them as part of the clean up.

**Comment by FaithOmbongi** [comment]
Hi @millicentachieng - We seem to have a regression of this issue. Occurs in both beta and v1.0.

See a demo PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/24085.

Can you reopen this bug so we can track?

Also, @lauraga had a great suggestion - can we have a global suppressions file instead of adding suppressions to individual files? If it's possible, LMK and I'll file a fresh bug for it.
