### ISSUE TITLE
certificate for api backend (*.azurewebsites.net) is not valid

### ISSUE THREAD

**Issue by nziegler** [microsoftgraph/microsoft-graph-devx-api#1686]
**Describe the bug**
When opening the graph explorer website from within my company, the control panel in the center of the website fails to load, because the certificate for the api that it tries to contact is not valid.

 GET https://graphexplorerapi.azurewebsites.net/openapi/tree net::ERR_CERT_AUTHORITY_INVALID.
 See the screenshot for certificate details.

Our company proxy will only recognize it as valid if the certificate was issued by a public trusted CA, but it is currently issued by a proxy network device. (See second screenshot)

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. See in website window that graph explorer controls do not load
3. Click on developer tools (F12)
4. Open Console
5. See certificate error

**Expected behavior**
The graph explorer controls should be visible and usable

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/20949641/6db4325e-80af-417c-8780-1667151367e6)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/20949641/6551151f-240b-4004-be46-7dc358ae7cc4)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 114.0.5735.199
Does not work in any browser.

**Additional context**
Our company proxy (financial services company) does not allow to load websites with invalid certificates.

**Comment by irvinesunday** [comment]
A quick current check on the certificate info. for https://graphexplorerapi.azurewebsites.net/openapi/tree shows the CA issuer to be Microsoft Azure
![image](https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/40403681/6d6d385f-d64b-4c6d-8ad0-3424dfc65f59)

The backend API runs on a default domain (`<app-name>.azurewebsites.net`) and uses a wildcard certificate issued by Azure

@nziegler are you still experiencing this problem?

**Comment by nziegler** [comment]
Then it must be an internal problem. The "Blue Coat" network device seems to have replaced the original certificate. I was sure it would be our internet policy not allowing the api to load. Should have confirmed from outside the network if I was the same certificate.
