### ISSUE TITLE
Detect, Flag, and raise a blocking error when examples have "canary", "ppe", or non-v1 and non-beta references

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#1811]
**Is your feature request related to a problem? Please describe.**
During content authoring, the PR author may use an internal private environment to test the APIs and document the examples in the API docs. Unfortunately, sometimes they forget to replace instances like `https://canary.graph.microsoft.com/testprodbetaevan_schema/` with `https://graph.microsoft.com/beta/`. Some of these cases may also be missed by content reviewers.

Some cases that have leaked into docs:

- "https://canary.graph.microsoft.com/testprodbetaevan_schema/" - contains both canary and non-beta, non-v1
- "https://graph.microsoft-ppe.com/beta/" - contains ppe

**Describe the solution you'd like**
API Doctor to explicitly flag URLs in the Examples section that don't start with "https://graph.microsoft.com/beta/" or "https://graph.microsoft.com/v1.0/".

**Describe alternatives you've considered**
None.

**Additional context**
None.

cc @millicentachieng

**Comment by millicentachieng** [comment]
@FaithOmbongi We will need to fix the existing issues in the docs first before we can effect this change.

See logs for v1.0 [here](https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=132676&view=logs&j=42ffaf55-b604-5aba-6f09-9cf394fd974a&t=547a3804-5a4f-52a8-6a4d-59f7bd332386).
