### ISSUE TITLE
Generate code snippets for bitLocker docs where examples contain custom headers

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-devx-api#1842]
Currently, the docs for BitLocker [LIST](https://learn.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-1.0#examples) and [GET](https://learn.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-1.0#examples) APIs don't have code snippets. I'm not sure if the custom headers are the cause of this issue (please correct the issue title if not).

Please generate code snippets for the operations. Thank you.

Related issue https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8830

**Comment by andrueastman** [comment]
@FaithOmbongi I believe the parsing is failing due to the quotation marks on the header values. We should remove them first so that snippets can be generated. The headers values should not be in quotation marks similar to the ConsistencyLevel header [here](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#request-3)

```http
GET https://graph.microsoft.com/v1.0/informationProtection/bitlocker/recoveryKeys?$filter=deviceId eq '1ab40ab2-32a8-4b00-b6b5-ba724e407de9'
User-Agent: Dsreg/10.0 (Windows 10.0.19043.1466)
ocp-client-name: My Friendly Client
ocp-client-version: 1.2
```

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi I believe the parsing is failing due to the quotation marks on the header values. We should remove them first so that snippets can be generated. The headers values should not be in quotation marks similar to the ConsistencyLevel header [here](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#request-3)
> 
> ```httpspec
> GET https://graph.microsoft.com/v1.0/informationProtection/bitlocker/recoveryKeys?$filter=deviceId eq '1ab40ab2-32a8-4b00-b6b5-ba724e407de9'
> User-Agent: Dsreg/10.0 (Windows 10.0.19043.1466)
> ocp-client-name: My Friendly Client
> ocp-client-version: 1.2
> ```

Ah, gotcha, @andrueastman.
Let me raise a PR today to apply your suggestion so we can see if the snippets get generated in the next round. I'll revert back to this thread.

**Comment by andrueastman** [comment]
Resolved via https://github.com/microsoftgraph/microsoft-graph-docs/pull/23102
