### ISSUE TITLE
Refactor snippet generation to use new methods after backwardcompatible changes

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-devx-api#1880]
A number of methods/types have been marked obsolete after backwardcompatible changes in the Kiota generator. We will need to refactor the snippet generation to use the new types to avoid confusion due to this.

Sourced from https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2244

**Comment by fey101** [comment]
Snippet Gen:
Dev:
 - passed - 3542
- Failed - 286
- Beta Passed = 3798
- Beta Failed = 598

PR:
- passed - 3544
- Failed - 284
- Beta Passed = 3801
- Beta Failed = 595 

References: 
Dev: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=136410&view=logs&j=8fa2a7e2-02f7-55ed-e836-ee67ef03db1e&t=7be20696-8a5d-5513-555e-2eb92a33e782

PR: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=136446&view=logs&s=fdb63226-3c98-58e9-3a21-c24350db8bb4
