### ISSUE TITLE
[Python] Align snippet generation to specification.

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-devx-api#1937]
Specification for snippets should align to the specification available at https://gist.github.com/sebastienlevert/ae40eb334c3d5a9d4cd3f4a06d2b09be and shared document.

In summary, we should update snippets to

- [x]  Have necessary import statements
- [x]  Remove client initialization code
- [x]  Add comments with links
- [x]  Display version of SDK the snippet supports.

**Comment by shemogumbe** [comment]
This was related to work on snippets on DevX api which is done:
Request adapter was removed
Snippets were added
comments and version were added
