### ISSUE TITLE
Code snippets don't handle OData casts properly

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-devx-api#211]
https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=csharp#example 
[AB#7019](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7019)

**Comment by andrueastman** [comment]
This is part of https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/146 as well

**Comment by zengin** [comment]
closing this to track in #146
