### ISSUE TITLE
`inheritedFrom` property is empty for Permission in Files 

### ISSUE THREAD

**Issue by salexln** [microsoftgraph/microsoft-graph-devx-api#223]
I'm doing the following `GET` call:

`https://graph.microsoft.com/beta/users/{user_id}/drive/items/{item_id}/permissions`

and the response I get is:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('{user_id}')/drive/items('{item_id}')/permissions",
    "value": [
        {
            "id": "{permission_id}",
            "roles": [
                "owner"
            ],
            "grantedTo": {
                "user": {
                    "email": "User email",
                    "id": "user_id",
                    "displayName": "User name
                }
            },
            "inheritedFrom": {}
        }
    ]
}
```
and even thought this item inherits it's permissions, I still get `inheritedFrom: {}`

(if the permission a unique and not inherited, `inheritedFrom` does not show at all.) 
[AB#7022](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7022)

**Comment by millicentachieng** [comment]
Hi @salexln,

Thank you for reporting your concern. Unfortunately, we do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
