### ISSUE TITLE
[OpenAPI] Translate permissions annotations in CSDL to OpenAPI

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-devx-api#277]
There's need to get ready for the work Identity team is investing in to have permissions in CSDL, and to do this, we need to convert the current document we are using to CSDL annotation and then consume it from our Open API SDK in DevX API. This way when the permissions are available in CSDL, we will just change Jackson's file and replace it with the new file.  
[AB#7029](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7029)

**Comment by ddyett** [comment]
@irvinesunday is this still work we need.

**Comment by petrhollayms** [comment]
@irvinesunday, @millicentachieng - is this still needed or can we close it as outdated?

**Comment by irvinesunday** [comment]
Our permission story has changed since this issue was created. We can go ahead and close this.
