### ISSUE TITLE
Open types should use additional data for non-existent properties

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#296]
`Identity` doesn't have `TenantId` and `InvitationParticipantInfo` doesn't have `LanguageId` and `Region` in the following example:
```csharp
var transferTarget = new InvitationParticipantInfo
{
    EndpointType = EndpointType.Default,
    Identity = new IdentitySet
    {
        User = new Identity
        {
            Id = "550fae72-d251-43ec-868c-373732c2704f",
            TenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47",
            DisplayName = "Heidi Steen"
        }
    },
    LanguageId = "languageId-value",
    Region = "region-value",
    ReplacesCallId = "replacesCallId-value"
};
```

Both are open types and we should add these properties into AdditionalData.
https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&tabs=csharp#request 
[AB#6989](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6989)

**Comment by fey101** [comment]
The main fix lies in addressing https://github.com/microsoftgraph/microsoft-graph-docs/issues/12184
