### ISSUE TITLE
Response schemas of actions and functions that return a collection are not accurately described

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#307]
The current OpenAPI response schemas for delta functions is wrong. e.g.
`/applications/microsoft.graph.delta()` currently returns an array of applications and not a response object with a collection of application as described in the docs - https://docs.microsoft.com/en-us/graph/api/application-delta?view=graph-rest-1.0&tabs=http#response-1.
![image](https://user-images.githubusercontent.com/7061532/91593561-41751a80-e915-11ea-9617-7cc7718c1453.png)

This should ideally be represented as a collection of application wrapped in a value property of the response object:
```yaml
/applications/microsoft.graph.delta():
    get:
      tags:
        - applications.Functions
      summary: Invoke function delta
      operationId: applications_delta
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                title: Collection of application
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.directoryObjectapplication'
                  '@odata.nextLink':
                    type: string
                additionalProperties:
                  type: object
```
 
[AB#6986](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6986)

**Comment by peombwa** [comment]
The same applies to all delta functions.

**Comment by peombwa** [comment]
This also affects `/directoryObjects/{directoryObject-id}/microsoft.graph.getMemberObjects`, see https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0&tabs=http#response-1.

**Comment by peombwa** [comment]
Any feedback on this?

**Comment by irvinesunday** [comment]
@peombwa this was fixed in this PR: https://github.com/microsoft/OpenAPI.NET.OData/issues/116 
It is already in `v1.0.9` which is yet to be updated in DevX API due to the underlying navigation property paths expansion issue.

**Comment by peombwa** [comment]
Was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0
