### ISSUE TITLE
Snippet generation needs to add support for multiple namespaces (Java)

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-devx-api#325]
[AB#6985](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6985)

**Comment by baywet** [comment]
@andrueastman  @zengin AFAIK the snippet generation doesn't add any import in Java or using in dotnet, is there anything that needs to be done at this point?

**Comment by zengin** [comment]
In C#, the assumption was that `using namespace Microsoft.Graph` is always added to the outer decoration. So the solution was to add fully qualified names for types outside Microsoft.Graph namespace.

I don't think the same approach works well with Java given that fully qualified names are really long.

For automated tools, like Raptor compilation tests, we can either import model and request namespaces for all subnamespaces or we can determine the necessary imports on the fly.

Subnamespace samples are not yet reenabled.

https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0


I had this in my TODO list, but I created an issue as I haven't found time to get to it yet: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/137

**Comment by ddyett** [comment]
@ramsessanchez please update PR which addressed this and close.
