### ISSUE TITLE
Snippet Generation for CallRecords (and possibly other subnamespaces)

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#367]
We don't generate snippets for CallRecords documentation. Example page:
https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0 
[AB#6997](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6997)

**Comment by fey101** [comment]
Addressed in merged PR.
