### ISSUE TITLE
Some webUrl to sharepoint return 404 on Beta search

### ISSUE THREAD

**Issue by eding178** [microsoftgraph/microsoft-graph-devx-api#373]
[AB#7001](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7001)

**Comment by darrelmiller** [comment]
This is not the best location to get answers to questions like this. I would recommend posting in Microsoft Q&A forums. https://docs.microsoft.com/en-us/answers/products/
