### ISSUE TITLE
Some search with beta Search return duplicate objects including same id

### ISSUE THREAD

**Issue by eding178** [microsoftgraph/microsoft-graph-devx-api#374]
exacly the same object including id BUT diferent webUrl 
[AB#6999](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6999)

**Comment by darrelmiller** [comment]
Hi eding178,

Can you tell use which Search function on the Graph you are trying to use?  Also, this is not the best location to get answers to questions like this.  I would recommend posting in Microsoft Q&A forums.  https://docs.microsoft.com/en-us/answers/products/
