### ISSUE TITLE
[Feature Request] Support regex-based filtering on operationIds query parameter

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#441]
It would be nice to support a regex-based filtering on operationIds query parameter. This will make it easier for PS SDK and future SDKs to narrow down on a subset of APIs. This can be similar to what we currently have for tags.

e.g. 
This is currently not supported `https://graphexplorerapi.azurewebsites.net/openapi?operationIds=deviceManagement.reports*`.

**Comment by darrelmiller** [comment]
@peombwa   Can you give an example of where you might want this?

**Comment by millicentachieng** [comment]
This will be done in Hidi https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/802#issuecomment-983722081
