### ISSUE TITLE
Query parameters with spaces cause snippet generation to fail

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-devx-api#445]
For example:

## Request

```
POST https://graphexplorerapi.azurewebsites.net/snippetgenerator?lang=C%23

GET /v1.0/users?$filter=displayName eq 'Megan Bowen'&$select=displayName,id,mail HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json

{}
```

## Response

```
400 Bad Request

Error parsing HTTP message header byte 38 of message System.Byte[].
```

This causes Graph Explorer to show "Snippet not available". The query (with spaces) runs fine though. Since the query is valid, Graph Explorer shouldn't fail to generate the snippet.

## Workaround

You can workaround this by escaping spaces with %20 in the API (but not in Graph Explorer). Graph Explorer seems to replace %20 with space before calling the API.

```
POST https://graphexplorerapi.azurewebsites.net/snippetgenerator?lang=C%23

GET /v1.0/users?$filter=displayName%20eq%20'Megan%20Bowen'&$select=displayName,id,mail HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json

{}
```
 
[AB#8048](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8048)

**Comment by baywet** [comment]
@adhiambovivian just ran into that today again. It's been almost a year since this bug has been logged. Can we do something about it?

Another example of that is 

```
https://graph.microsoft.com/v1.0/users?$select=displayName,id,jobTitle,mail&$orderBy=displayName desc&$top=10
```

where the space before the desc makes the generation fail.

**Comment by njaci1** [comment]
I have tried both scenarios and got a response and snippets. Allow me to mark the issue as closed.

**Comment by baywet** [comment]
thanks for circling back on this one. Closing.
