### ISSUE TITLE
$filter clause is generated incorrectly when other query parameters are present

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-devx-api#446]
For example:

## Request

```
POST https://graphexplorerapi.azurewebsites.net/snippetgenerator?lang=C%23

GET /v1.0/users?$filter=mailNickName%20eq%20'meganb'&$select=displayName,id,mail HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json

{}
```

## Response

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var users = await graphClient.Users
	.Request()
	.Filter("mailNickName eq 'meganb',")
	.Select("displayName,id,mail")
	.GetAsync();
```

Notice the extra `,` inside the double-quotes in the `.Filter` function's parameter. 
[AB#8049](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8049)

**Comment by jasonjoh** [comment]
This is an issue with the version currently deployed. The current code in dev seems to have fixed this as I don't see the problem when I run the code locally.

**Comment by irvinesunday** [comment]
@jasonjoh thanks for spotting this; the [fix](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/438/files) will be deployed to production this week.
