### ISSUE TITLE
"Try it out" button for snippetgenerator on Swagger UI always fails with 415

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-devx-api#458]
Repro:

1. Go to https://graphexplorerapi.azurewebsites.net/swagger/index.html
2. Expand **POST /snippetgenerator**
3. Select **Try it out**
4. Select **Execute**

Result: Server returns 415.

It looks like the UI is passing the wrong `Content-Type`. The UI has `text/message;version=1.1;msgtype=request`. However, the API endpoint is expecting `application/http`. 
[AB#8087](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8087)

**Comment by ddyett** [comment]
this issue appears to be fixed.
