### ISSUE TITLE
[Snippet Generation] Case of property segments in URLs are not handled

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-api#485]
In current C# SDK, request builders only navigation properties defined as their properties. We should generate using `AppendSegmentToRequestUrl`.

Example:
```http
PUT https://graph.microsoft.com/beta/identity/b2cUserFlows/B2C_1_testuserflow/apiConnectorConfiguration/postFederationSignup/$ref
```

`apiConnectorConfiguration` is a property of `b2cIdentityUserFlow` (not a navigation property).

https://docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-put-apiconnectorconfiguration?view=graph-rest-beta&tabs=http#request

Current C# generation skips the URL segment altogether if it is a property, so we end up with:
```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.Identity.B2cUserFlows["B2C_1_testuserflow"].PostFederationSignup.Reference
	.Request()
	.PutAsync("{id}");
``` 
[AB#8319](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8319)

**Comment by fey101** [comment]
Another similar example: 
```http
PUT https://graph.microsoft.com/beta/servicePrincipals/{id}/synchronization/secrets
Content-type: application/json

{
    "value": [
        {
            "key": "BaseAddress",
            "value": "user@domain.com"
        },
        {
            "key": "SecretToken",
            "value": "password-value"
        },
        {
            "key": "SyncNotificationSettings",
            "value": "{\"Enabled\":false,\"DeleteThresholdEnabled\":false}"
        },
        {
            "key": "SyncAll",
            "value": "false"
        }
    ]
}
``` 
Generated Snippet:
``` C#

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var secrets = new SynchronizationSecretKeyStringValuePair
{
	Value = new List<String>()
	{
		"",
		"",
		"",
		""
	}
};

await graphClient.ServicePrincipals["{servicePrincipal-id}"].Synchronization
	.Request()
	.PutAsync(secrets);
```

**Comment by zengin** [comment]
Main discussion on this issue is here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1003

**Comment by andrueastman** [comment]
Closing this for now as this is a metadata issue tracked via https://github.com/microsoftgraph/msgraph-metadata/issues/371.
Property segments referenceable through the URL should be annotated in the metadata as captured in https://github.com/microsoft/OpenAPI.NET.OData/issues/176
