### ISSUE TITLE
[PowerShell] /applicationTemplates/{applicationTemplate-id}/microsoft.graph.instantiate should return 201

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#492]
[/applicationTemplates/{applicationTemplate-id}/microsoft.graph.instantiate](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Applications.yml#L2250-L2286) path should return HTTP status`201` instead of `200`.
### Current response
![image](https://user-images.githubusercontent.com/7061532/110359753-b6c35580-7ff2-11eb-9b42-b258954ced35.png)

### Expected response
https://docs.microsoft.com/en-us/graph/api/applicationtemplate-instantiate?view=graph-rest-1.0#response-1 
[AB#8474](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8474)

**Comment by darrelmiller** [comment]
PowerShell should handle both 201 and 200 even if the OpenAPI only documents one.  There is no way for the CSDL to tell us which status code a service might return.  We should be prepared for both.  Ideally the OpenAPI description should use "2XX"

**Comment by irvinesunday** [comment]
@peombwa do you think this should be closed based on @darrelmiller's response above?

**Comment by peombwa** [comment]
The AutoREST team recently added [wildcard response code support](https://github.com/Azure/autorest.powershell/pull/881) to AutoREST.PowerShell v3 as described in https://spec.openapis.org/oas/latest.html#responses-object. Therefore, we should update our OpenAPI files to represent success response codes as a wildcard to address this issue.

See the discussion in https://github.com/Azure/autorest.powershell/issues/853.

**Comment by peombwa** [comment]
Wildcard support was added by conversion lib in v1.0.10. PowerShell will support this in v2 when we move to AutoREST v3.

We are tracking this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907.
