### ISSUE TITLE
[Snippet Generation] Add support for $count query parameter in snippets

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-devx-api#497]
The example request at this link has a query parameter of $couint. However, this is not reflected in the respective snippets as being added as query option values. 

https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#request-4 
[AB#8525](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8525)

**Comment by zengin** [comment]
fixed by SDK v5, can you please confirm @andrueastman?

**Comment by andrueastman** [comment]
Confirmed. This can be closed.
