### ISSUE TITLE
Delta namespace Prefix

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-devx-api#498]
Alias delta calls with the corresponding namespace.
For example:-

Fails with the following message:-
```
https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/me/calendarView/microsoft.graph.delta()&method=GET
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-1db509cb5f36db4681eef8b217e8a539-4244664b6f330f46-00"}
```
however removing `microsoft.graph` resolves the issue.
```
https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/me/calendarView/delta()&method=GET
[{"value":"Calendars.Read","consentDisplayName":"Read your calendars ","consentDescription":"Allows the app to read events in your calendars. ","isAdmin":false}]
```
 
[AB#8529](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8529)

**Comment by darrelmiller** [comment]
Seems to be an issue when looking up the permission from the request URL.  We should look for both qualified and unqualified names in the permissions doc.

**Comment by irvinesunday** [comment]
Resolved by: https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/585
