### ISSUE TITLE
Mark Read Only Props as readOnly: true

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-devx-api#532]
The --id property  -- at the bottom -- is generated as an argument although users won't have to pass it to the command because it is a readonly property, this is undesirable as it clutters the arguments. To avoid readonly properties from being generated they should be marked as `readOnly: true` in the OpenAPI definition.

<img width="843" alt="Screen Shot 2021-04-14 at 10 43 20 AM" src="https://user-images.githubusercontent.com/12011447/114672846-3f2dc800-9d0e-11eb-9ff6-0dc008ae3568.png">
 
[AB#8982](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8982)

**Comment by millicentachieng** [comment]
Fixed by https://github.com/microsoft/OpenAPI.NET.OData/issues/254
