### ISSUE TITLE
Implement the resources explorer endpoint

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-devx-api#537]
The resources explorer endpoint is going to pick the open API resources from the OpenAPI endpoint and create a tree that will be consumed by Graph Explorer (and may be AGORA) 
[AB#9012](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9012)

**Comment by adhiambovivian** [comment]
This was completed
