### ISSUE TITLE
Fix function/actions paths OperationId in PowerShell style

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#543]
This [fix](https://github.com/microsoft/OpenAPI.NET.OData/pull/98) in the `OpenAPI.OData` lib. caused breaking changes to PowerShell.

**Current experience:**
![image](https://user-images.githubusercontent.com/40403681/115688562-f0aea800-a363-11eb-8f1b-5653ba515dc4.png)

**Expected experience** from PowerShell (to avoid breaking change)
![image](https://user-images.githubusercontent.com/40403681/115688740-16d44800-a364-11eb-8554-4e81bd09626b.png)

Notice the different OperationIds. The 1st experience breaks existing PowerShell clients, as this is a breaking change. 

We need to revert this by providing a fix in the `Style = PowerShell` option in the `OpenApiService` in DevX API to revert OperationId. This is happening on version `1.0.7` of the `OpenAPI.OData` lib. 
[AB#9127](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9127) 
AB#undefined

**Comment by darrelmiller** [comment]
If I understand what change has happened here, it appears that the type of the binding parameter is no longer included in the function name.  That seems like a bad idea.  If that is dropped then we are going to get name clashes.
