### ISSUE TITLE
Technical debt on Devx API

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-devx-api#548]
Configuring Sonarcloud in our repo surfaced a couple of quality gaps within our codebase as portrayed in the snapshot below:

![image](https://user-images.githubusercontent.com/36787645/133323786-38052950-f27d-4a4e-aa7b-8bfb584b802b.png)

This issue will address the following work items:
  - Deprecate some code in DevX API e.g authentication.
  - Review and address any security issue
  -  Fix bugs present
  -  Increase code coverage to 80%
  -  Reduce code smells 
  - Remove duplicated code blocks

Related : #666, #706, #707
[AB#9202](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9202)

**Comment by adhiambovivian** [comment]
This was completed
