### ISSUE TITLE
Migrate OpenAPI project pipelines

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#554]
We need to migrate the OpenAPI project pipelines from https://msazure.visualstudio.com/OpenApi/_build?definitionId=19888 to https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build
 
[AB#9279](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9279)

**Comment by darrelmiller** [comment]
Talk to @MIchaelMainer about this.  He and I discussed this move the other day.

**Comment by MIchaelMainer** [comment]
Here's the pipeline: https://github.com/microsoft/OpenAPI.NET/pull/586. It is setup to run on commit into `master`. Once the generated packages have been reviewed, and our team has shared ownership of the NuGet packages, we can finalize the release definition.
