### ISSUE TITLE
Missing $ref paths for DELETE operations

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#567]
A number of paths are missing `$ref` paths for DELETE operation. e.g. 
![image](https://user-images.githubusercontent.com/7061532/118050517-47404e00-b334-11eb-9938-97985cde265b.png)

Some of the missing $ref paths are:
- `DELETE /applications/{application-id}/owners/$ref` - [docs](https://docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-1.0&tabs=http#http-request).
- `DELETE /groups/{group-id}/members/{member-id}/$ref` - [docs](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http#http-request).
- `DELETE /groups/{group-id}/owners/{owner-id}/$ref` - [docs](https://docs.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=http#http-request). 

Related to:
- https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/452
- https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/660

[AB#9454](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9454)

**Comment by darrelmiller** [comment]
The first example is broken because you should not be able to delete a collection.
The other two examples are not generated because they are containsTarget=false and we don't expand those.  We can't do any better until we get a IndexableByKey capability annotation in the metadata for all navigation properties to collections.

**Comment by peombwa** [comment]
@darrelmiller My bad, I used the wrong example for the first one. We are missing `DELETE /applications|servicePrincipals/{id}/owners/{id}/$ref` - [docs](https://docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-1.0&tabs=http#http-request).

**Comment by peombwa** [comment]
Also missing:
- `DELETE /servicePrincipals/{id}/claimsMappingPolicies/{id}/$ref`

**Comment by peombwa** [comment]
@darrelmiller Isn't `IndexableByKey=true` by default? See https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.xml#L303. This means that we should already be treating all navigation properties to collection that do not have `IndexableByKey` annotation as `IndexableByKey=true` in `OpenAPI.NET.OData` lib. I'm not sure if this is the case.

Also, `OpenAPI.NET.OData` should be updated to handle cases where `IndexableByKey=true` and a navigation property `is contained` - https://github.com/microsoft/OpenAPI.NET.OData/blob/e8ecb37c96e42b3c744bbbe5430428134b9906de/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L273-L302.

cc\ @irvinesunday

**Comment by irvinesunday** [comment]
> @darrelmiller Isn't `IndexableByKey=true` by default? See https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.xml#L303. This means that we should already be treating all navigation properties to collection that do not have `IndexableByKey` annotation as `IndexableByKey=true` in `OpenAPI.NET.OData` lib. I'm not sure if this is the case.
> 
> Also, `OpenAPI.NET.OData` should be updated to include `DELETE ~/entityset/{key}/collection-valued-Nav/{navKey}/$ref` for case where `IndexableByKey=true` and a navigation property `is non-contained` since this is what MS Graph uses - https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L274-L302.
> 
> cc\ @irvinesunday

You're right @peombwa, the `OpenAPI.NET.OData` lib. treats all navigation properties to collection that do not have the `IndexableByKey` annotation as `IndexableByKey=true`, see: https://github.com/microsoft/OpenAPI.NET.OData/blob/e8ecb37c96e42b3c744bbbe5430428134b9906de/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L273-L274

And yes, we should be generating the paths `~/entityset/{key}/collection-valued-Nav/{navKey}/$ref` here: https://github.com/microsoft/OpenAPI.NET.OData/blob/e8ecb37c96e42b3c744bbbe5430428134b9906de/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L278-L283

**Comment by maisarissi** [comment]
Hi @irvinesunday .

The DELETE operation is still missing in the OpenAPI document.

**Comment by ryanchrisw** [comment]
Any updates on this?

**Comment by adhiambovivian** [comment]
@maisarissi  @ryanchrisw this has been resolved in the[ OData library version 1.0.10.](https://github.com/microsoft/OpenAPI.NET.OData/pull/112)

**Comment by maisarissi** [comment]
Hi @ryanchrisw . We have a tool chain when generating the PS SDK. So, the OData lib version 1.0.10 (which @adhiambovivian pointed out that fixes this issues) was released, but we still need to update the tool that converts OData to OpenAPI so the PS SDK can use the updated OpenAPI document in its generation.

**Comment by maisarissi** [comment]
Depends on https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/902.

**Comment by peombwa** [comment]
`Remove-Mg*` commands are now available as of https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0.
