### ISSUE TITLE
OData functions returning OData-structured JSON objects not raw arrays for collections break OpenAPI-based parsers

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/microsoft-graph-devx-api#571]
As an OData function, 
`https://graph.microsoft.com/beta/reports/microsoft.graph.getCredentialUsageSummary(period='D1')`
returns 
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(credentialUsageSummary)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.credentialUsageSummary",
            "id": "b2a991b2-5a04-4f45-959f-44cae3ffd0d4", ...
```

`beta_metadata.xml` has
```
<Function Name="getCredentialUsageSummary" IsBound="true" IsComposable="true">
        <Parameter Name="reportRoot" Type="graph.reportRoot" />
        <Parameter Name="period" Type="Edm.String" Nullable="false" Unicode="false" />
        <ReturnType Type="Collection(graph.credentialUsageSummary)" Nullable="false" />
      </Function>
```
However, 
`https://graphexplorerapi.azurewebsites.net/openapi?operationIds=reports.getCredentialUsageSummary&openApiVersion=3&graphVersion=beta`
I believe is interpreting that literally, and generating 

```
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/microsoft.graph.credentialUsageSummary'
```

whereas the service's response is formatted according to OData, where

> Each message body is represented as a single JSON object. This object is either ... or it contains a name/value pair whose name MUST be value and whose value is the correct representation for ... a collection of entities, or a collection of objects that represent changes to a previous result.

I would have expected the openAPI response for success to be
```
          content:
            application/json:
              schema:
                title: Collection of credentialUsageSummary
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.credentialUsageSummary'
                  '@odata.nextLink':
                    type: string
                additionalProperties:
                  type: object
```
to match the OData function definition.

This breaks autogenerated graph PSh use of the YAML file -derived parser which fails as it is expecting an array rather than an object for this and other functions.
 
[AB#9493](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9493)

**Comment by darrelmiller** [comment]
@markwahl-msft  Thanks for reporting this.  This seems like it is an issue with the OData - OpenApi converter library.   @irvinesunday Could you open an issue for this?  Thanks.

**Comment by peombwa** [comment]
Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/307.

**Comment by peombwa** [comment]
Was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0.
