### ISSUE TITLE
Support namespacing of odata.type values without the hash symbol

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#580]
When the odata.type annotation's value is specified without the hash symbol, and the value is not within the Microsoft.Graph namespace, the output of the snippet generated class should be namespaced. This is already supported for values specified with the hash symbol, but it also has to be inclusive of values specified without the hash symbol.

In the example below notice that the settings `odata.type` is specified without the '#' symbol. The expected snippet generated should still namespace the `WindowsDeploymentSettings` as `Settings = new microsoft.graph.windowsUpdates.windowsDeploymentSettings`

sample http snippet input 
```http
{
  "@odata.type": "#microsoft.graph.windowsUpdates.deployment",
  "settings": {
    "@odata.type": "microsoft.graph.windowsUpdates.windowsDeploymentSettings",
    "monitoring": {
      "monitoringRules": [
        {
          "signal": "rollback",
          "threshold": 5,
          "action": "pauseDeployment"
        }
      ]
    }
  }
}
```

Should generate
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var deployment = new Microsoft.Graph.WindowsUpdates.Deployment
{
	Settings = new microsoft.graph.windowsUpdates.windowsDeploymentSettings
	{
		Monitoring = new Microsoft.Graph.WindowsUpdates.MonitoringSettings
		{
			MonitoringRules = new List<Microsoft.Graph.WindowsUpdates.MonitoringRule>()
			{
				new Microsoft.Graph.WindowsUpdates.MonitoringRule
				{
					Signal = Microsoft.Graph.WindowsUpdates.MonitoringSignal.Rollback,
					Threshold = 5,
					Action = Microsoft.Graph.WindowsUpdates.MonitoringAction.PauseDeployment
				}
			}
		}
	}
};

await graphClient.Admin.Windows.Updates.Deployments["{windowsUpdates.deployment-id}"]
	.Request()
	.UpdateAsync(deployment);
```
instead of 
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var deployment = new Microsoft.Graph.WindowsUpdates.Deployment
{
	Settings = new WindowsDeploymentSettings
	{
		Monitoring = new Microsoft.Graph.WindowsUpdates.MonitoringSettings
		{
			MonitoringRules = new List<Microsoft.Graph.WindowsUpdates.MonitoringRule>()
			{
				new Microsoft.Graph.WindowsUpdates.MonitoringRule
				{
					Signal = Microsoft.Graph.WindowsUpdates.MonitoringSignal.Rollback,
					Threshold = 5,
					Action = Microsoft.Graph.WindowsUpdates.MonitoringAction.PauseDeployment
				}
			}
		}
	}
};

await graphClient.Admin.Windows.Updates.Deployments["{windowsUpdates.deployment-id}"]
	.Request()
	.UpdateAsync(deployment);
```

 
[AB#9557](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9557)

**Comment by fey101** [comment]
Related docs pages:

https://docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&tabs=csharp (should namespace windowsDeploymentSettings)

https://docs.microsoft.com/en-us/graph/api/windowsupdates-updates-post-deployments?view=graph-rest-beta&tabs=csharp#request (The featureUpdateReference and the windowsDeploymentSettings should be namespaced)

https://docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-post?view=graph-rest-beta&tabs=csharp#request (userSource should be namespaced)

**Comment by zengin** [comment]
fixed in SDK v5 snippets.
