### ISSUE TITLE
Graph Explorer does not show any permissions for callRecords GET query

### ISSUE THREAD

**Issue by hthomassen** [microsoftgraph/microsoft-graph-devx-api#608]
The following problem has been observed after signing into Graph Explorer with a user account that has Global Administrator Role in a particular tenant. The same user was able to perform a GET query to retrieve Teams Usage Reports, grant the required permission CallRecords.Read.All and Grant Admin consent.

### Steps to reproduce the behavior

When executing the GET query https://graph.microsoft.com/beta/communications/callRecords/[CallID] in Graph Explorer, the following 403 is Received:

Forbidden - 403 - 224 ms. You need to consent to the permissions on the Modify permissions tab.

### Expected behavior

After clicking the Modify permissions tab, to be presented with a list of permissions, similar to the list shown below, among which the permission CallRecords.Read.All.

### Actual behavior

After clicking the Modify permissions tab, this tab appears empty.
 
[AB#9915](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9915)

**Comment by irvinesunday** [comment]
The endpoint `/beta/communications/callRecords/{callRecord-id}` requires app-only permission `CallRecords.Read.All`. Graph Explorer currently only exposes delegated permissions.

**Comment by millicentachieng** [comment]
> The endpoint `/beta/communications/callRecords/{callRecord-id}` requires app-only permission `CallRecords.Read.All`. See doc. [ref](https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http#permissions). Graph Explorer currently only exposes delegated permissions. This means you cannot call this endpoint from Graph Explorer.

I'm closing the issue. Please reopen if further discussion is necessary.
