### ISSUE TITLE
Missing OData parameters in the latest OpenAPI refresh

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#611]
The most recent API refresh seemed to have removed some supported OData parameters from certain paths. e.g.
`GET \groups`, [which supports $filter](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#optional-query-parameters), is missing a `$ref: '#/components/parameters/filter` as its parameter. This results in AutoREST.PowerShell generating a `Get-MgGroup` command without a `-Filter` parameter. The same holds true for `$count` and `$skip`.

_Originally posted by @peombwa in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/703#discussion_r653065005_ 
[AB#9936](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9936)

**Comment by peombwa** [comment]
It looks like we've got duplicate capability annotations in the metadata, and it is not clear to me which one takes precedence over the other:
![image](https://user-images.githubusercontent.com/7061532/122301442-89b9f500-ceb5-11eb-8c90-b2de4e3851b6.png)

The annotations were added via https://github.com/microsoftgraph/msgraph-metadata/commit/2cedadaf36324b674d9880f44e65d88ca3aa6366.

**Comment by MIchaelMainer** [comment]
The duplicate capability annotations are present in the source metadata https://github.com/microsoftgraph/msgraph-metadata/blob/master/v1.0_metadata.xml

**Comment by peombwa** [comment]
@MIchaelMainer, @darrelmiller How can we escalate this to AGS or the affected workloads since this is a blocking issue? A workaround would be removing all annotations from the source metadata via XSLT and save it as `cleanMetadataWithDescriptionsWithNoAnnotationsv1.0.xml`.

cc\ @mairissi

**Comment by MIchaelMainer** [comment]
I suggest reaching out to Billy Odero. His team owns schema management.

**Comment by irvinesunday** [comment]
Closed by this PR: https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/624
