### ISSUE TITLE
Support for `DateTimeOffset` type values passed in the URL

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#612]
Related doc: https://docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&tabs=csharp#request

Sample input:
```http
GET https://graph.microsoft.com/beta/print/reports/getUserArchivedPrintJobs(userId='016b5565-3bbf-4067-b9ff-4d68167eb1a6',startDateTime=2021-05-24,endDateTime=2021-05-25)
```

Returned Output:
```C#

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var getUserArchivedPrintJobs = await graphClient.Print.Reports
	.GetUserArchivedPrintJobs("016b5565-3bbf-4067-b9ff-4d68167eb1a6","2021-05-24","2021-05-25")
	.Request()
	.GetAsync();
```

Expected Output:
``` C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var getUserArchivedPrintJobs = await graphClient.Print.Reports
	.GetUserArchivedPrintJobs(
                    "016b5565-3bbf-4067-b9ff-4d68167eb1a6",
                    DateTimeOffset.TryParse("2021-05-24"),
                    DateTimeOffset.TryParse("2021-05-25")
        )
	.Request()
	.GetAsync();
```

 
[AB#9955](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9955)

**Comment by rkodev** [comment]
@fey101 I can work on this issue

**Comment by andrueastman** [comment]
Just to follow up @zengin , this should be resolved with https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1468 as the openAPI SnippetModel failed to match a segment for such functions.

We can keep this open for now and re-evaluate on the next generation run on Tuesday.
