### ISSUE TITLE
Use restrictions capability annotations to specify operation level descriptions

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#615]
We can use the below capability annotations in the CSDL to specify operation level descriptions in the generated OpenAPI doc. for a target resource.
- `Org.OData.Capabilities.V1.UpdateRestrictions`
- `Org.OData.Capabilities.V1.ReadRestrictions`
- `Org.OData.Capabilities.V1.DeleteRestrictions`
- Org.OData.Capabilities.V1.ReadRestrictions

example:

Given the _user_ entity annotation target... 
![image](https://user-images.githubusercontent.com/40403681/122931637-be2a2700-d375-11eb-818f-75d1cac4ae5e.png)

We can add in restriction capability annotations with description properties. 
The generated OpenAPI document will have the operation level descriptions annotated in the restrictions annotation.
**NB:** The blue highlight description annotation will be the default description used across all the path operations for that resource if no restrictions annotation is specified for a given operation.

![image](https://user-images.githubusercontent.com/40403681/122932060-17925600-d376-11eb-986d-c10b23e640a1.png)

Now we have operation-level descriptions as annotated in the restrictions annotation in the CSDL.

 
[AB#10000](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10000)

**Comment by millicentachieng** [comment]
Fixed by https://github.com/microsoft/OpenAPI.NET.OData/pull/178
