### ISSUE TITLE
How to get one drive files that are shared by you using graph api?

### ISSUE THREAD

**Issue by JayachandraV** [microsoftgraph/microsoft-graph-devx-api#620]
We have an graph api to get one drive files that are "shared to you". But just wanted to understand if there is any possible way that get one drive files that are "shared by you".

Approach that we are following now:

Get all the drive files and folders from the root folder and target for shared property
But the cons of it is it should recursively search for each folder and have to call each folder in one drive with graph api to check for shared property. 
[AB#10036](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10036)

**Comment by millicentachieng** [comment]
I'm afraid the Microsoft Graph API does not have a direct endpoint to specifically query for OneDrive files that are shared by you.
