### ISSUE TITLE
Description of ContentBytes incorrect

### ISSUE THREAD

**Issue by lafe** [microsoftgraph/microsoft-graph-devx-api#629]
**Describe the bug**
Adding a new attachment to a message does not work as described in the [documentation](https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=csharp). The tooltip is also misleading:
![image](https://user-images.githubusercontent.com/4070008/118488886-7bdd4c80-b71c-11eb-972c-d3d41bdd4b2a.png)

Issue in both cases is that the `ContentBytes` property requires a "normal" byte array and not an encoded byte array. The Base64 encoding appears to be performed later. If the `ContentBytes` contain a Base64 encoded array, the value will be encoded twice in total and the resulting mail contains a Base64 result (for end users, this appears as gibberish).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the documentation and copy the [first C# example](https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=csharp#request):

   ```csharp
   GraphServiceClient graphClient = new GraphServiceClient( authProvider );
   
   var attachment = new FileAttachment
   {
   	Name = "smile",
   	ContentBytes = Encoding.ASCII.GetBytes("R0lGODdhEAYEAA7")
   };
   
   await graphClient.Me.Messages["{message-id}"].Attachments
   	.Request()
   	.AddAsync(attachment);
   ```

2. Implement it and run it
3. The resulting attachment to a file will contain the string `R0lGODdhEAYEAA7` instead of the desired GIF.

**Expected behavior**
The online documentation as well as the XML documentation of the `ContentBytes` property should not reference Base64 when using the .NET SDK.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: -
 - Version: 3.32 
[AB#9489](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9489)

**Comment by zengin** [comment]
@andrueastman, it looks like the v5 snippet refers to the base abstract type attachment and adds contentBytes into AdditionalData. Is this expected?

**Comment by andrueastman** [comment]
Snippet generation is using the schema at the url node which happens to be the base type in this situation. Will need to investigate if the typeHint/discriminator can be used to extract the derived type.
