### ISSUE TITLE
Refactoring OpenAPI Service

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoftgraph/microsoft-graph-devx-api#665]
- Refactoring code - e.g. autocomplete.
- Simplifies and performance tuning for OpenAPI generation.
- Slicing code for power platform. 
[AB#10767](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10767)

**Comment by adhiambovivian** [comment]
This was done.
