### ISSUE TITLE
Generate trimmed OpenAPI description for subset of Graph APIs that works with power platform based on the set of selected resources by a user. 

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-devx-api#723]
We can extend the current OpenAPI API endpoint on DevX API to accept 'power platform' as query parameter

**Comment by irvinesunday** [comment]
We are waiting for review from the Power Platform folks on this [document](https://microsoft.sharepoint-df.com/:w:/t/GraphTooling/Ease5K91AhpIrbAUOV1mccgBTQOVsuOxgUQLvBnuaXublw?e=5O7OWD&xsdata=MDN8MDF8fGFhZjI0YTBiMjQwNzQ1Y2Q4NDRkMDY2ZWU0NDljZGM3fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc3MTAyOTg2NzE3NjUxOTF8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=dDlXa2JjaTA2aWhpaVZEQm93TC9yTTVqdGhZL09nR0VyQWtQSVd4R0FPQT0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cirochand%40microsoft.com).

**Comment by millicentachieng** [comment]
Power Platform is currently supported,
