### ISSUE TITLE
Invalid `operationIds` for certain OData functions under `reports`.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#728]
**Describe the bug**
Certain operationIds for OData functions under `reports` entitySet have a weird suffix to them e.g., `reports_getSharePointSiteUsageDetail-204b`.

**To Reproduce**
- Go to https://graphexplorerapi.azurewebsites.net/openapi?tags=reports.Functions&openApiVersion=3&graphVersion=v1.0&format=yaml&style=PowerShell
- Inspect the returned OpenAPI document.
![image](https://user-images.githubusercontent.com/7061532/136273472-11606858-bc68-4eb8-ac6c-4e7097bc41d8.png)

**Expected behavior**
OperationIds should match the function names in the OData metadata.
![image](https://user-images.githubusercontent.com/7061532/136273983-5cbb0f73-c580-4a8f-a425-3b83e690c679.png)

**Comment by darrelmiller** [comment]
Possible suggestion: Could we add WithDate and WithPeriod to the end of the OperationId?  i.e. we use the set of parameter names as a unique suffix.

**Comment by irvinesunday** [comment]
@peombwa the suffix after the `operationId` is a hash value of the function name. This is appended to the `operationId`s of two or more overloaded `Functions` so as to avoid duplicates. 

@darrelmiller some [functions](https://graphexplorerapi.azurewebsites.net/openapi?operationIds=drive.list.items.listItem.getActivitiesByInterval-96b0&openApiVersion=3&graphVersion=v1.0&format=yaml&style=PowerShell) are parameter-less, so the option of using parameter name might not be feasible.
![image](https://user-images.githubusercontent.com/40403681/142846073-3b93fe3d-8919-42d0-9787-f3597fdcd58c.png)

Does PowerShell care much about this suffix or the naming of this suffix. If not, we can just remove these suffixes in the DevX API when processing the subset OpenAPI documents.

**Comment by darrelmiller** [comment]
@irvinesunday If the function is parameterless then there will not be a name clash.  OData requires the parameters to disambiguate between function names.  Therefore if there are no parameters then no suffix is required.

**Comment by peombwa** [comment]
@irvinesunday, is there a reason we need the hash to disambiguate duplicate `operationIds`?  Having `GET` operations that have duplicate `operationIds` and different parameter names is not an issue in PowerShell. AutoREST will generate an overload (parameterSet) if the `operationIds` are identical and the parameters are different.

AutoREST will only fail if the `operationIds` are identical and:
- The operations with duplicate `operationIds` have the same parameter names + type.
- The operation is `PUT`, `PATCH`, or `POST` (anything with a body in the request). So, OData actions will fail.

In this case, by dropping the hash suffix from `GET` operations, I can generate PowerShell commands for the functions above successfully as shown below:
![image](https://user-images.githubusercontent.com/7061532/142914691-115f5628-afab-43ab-bb70-89fe06fbd544.png)
![image](https://user-images.githubusercontent.com/7061532/142922326-ecfb81ac-f1b3-4182-a8e9-c94fc38fe9ad.png)

**Comment by irvinesunday** [comment]
Since the hash prefix is only appended to the `operationIds` of paths with overloaded functions, and functions expose only `GET` operations, going by the conditions that @peombwa has outlined that would lead to AutoREST failing in the case of duplicate `operationIds` then I think it would be best to strip out the hash suffix from `operationIds` in DevX API when serving subset OpenAPI docs for the PowerShell style option.

**Comment by peombwa** [comment]
@irvinesunday, the proposal sounds good to me. Keep me in the loop when the change is ready for testing.
