### ISSUE TITLE
Feature Request: Express Least to Most Privileged Permissions in Permissions API

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-devx-api#732]
**Is your feature request related to a problem? Please describe.**
The permissions table in Microsoft Graph Docs, lists permissions from "Least to Most Privileged".
![Permissions](https://user-images.githubusercontent.com/1641829/136470143-41ef975f-dd2c-45e1-a8f6-0ab972736631.jpg)
DevX API returns a list of permissions for the endpoint /users without expressing the idea of least to most privileged. However, DevX API returns Permissions in the following order, I also suspect that the order is not enforced and it can change depending on the underlying datastore and query.

`DeviceManagementApps.Read.All DeviceManagementManagedDevices.Read.All DeviceManagementServiceConfig.Read.All Directory.Read.All User.Read.All User.ReadBasic.All`

**Describe the solution you'd like**
Expressing the idea of least to most privileged would be useful in Raptor when selecting a Permission to use in PowerShell Scripts especially for Delegated Permissions. 
Either by an assurance that Permissions API will be deterministic in the order that it returns Permissions
To add a field indicating level of privilege, where say 1000 indicates very high and 1 very low.

**Comment by adhiambovivian** [comment]
Related to #1077
