### ISSUE TITLE
Permission Available in DevXContent Repo But Not Served Back in Graphexplorer Endpoint

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#752]
**Describe the bug**
This permission `PrintTaskDefinition.ReadWrite.All` is available in this file https://github.com/microsoftgraph/microsoft-graph-devx-content/blob/dev/permissions/permissions-descriptions.json but not served as a permission in [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) not by the graph explorer azure endpoint here https://graphexplorerapi.azurewebsites.net/permissions

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11347476/140017163-564fceee-9c0e-47a9-a978-eb286ef57289.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irvinesunday** [comment]
Hi @fey101 this particular permission is an **Application** permission. By default, GE requests for the **DelegatedWork** 
permissions, or **DelegatedPersonal** (if you are logged in with a personal account). 

![image](https://user-images.githubusercontent.com/40403681/140708337-72ee76d3-263c-4b8a-b579-af69620f6954.png)

Making the call https://graphexplorerapi.azurewebsites.net/permissions?scopeType=Application returns the above permission.

**Comment by fey101** [comment]
Thanks @irvinesunday , I will mark this as resolved for now and if any other related issues comes up, we will open a new issue and link it to this. Thanks for the prompt update.
