### ISSUE TITLE
How to set up development environment?

### ISSUE THREAD

**Issue by smerkx** [microsoftgraph/microsoft-graph-devx-api#755]
Hi,

Complete noob question here: I'm trying to set up a local dev environment to do some experiments based on this project.

I have stuff up-and-running, but it throws an error in PermissionsStore.cs line 65: "Exception has occurred: CLR/System.ArgumentNullException An exception of type 'System.ArgumentNullException' occurred in PermissionsService.dll but was not handled in user code: 'Config path missing: BlobStorage:Containers:Permissions'".

How do I configure this? And how do I get these files?

I looked at 'https://github.com/microsoftgraph/msgraph-permissions-scraper', somehow that seems to be related, but I just don't see how that fits in...

Can someone provide some more insights how to get a local instance of the GraphWebApi service up-and-running?

Thanks,
Stanley.

**Comment by MaggieKimani1** [comment]
Hi @smerkx, 
Can you please share a screenshot of your `appsettings.json` file?

**Comment by irvinesunday** [comment]
@smerkx have you set up your Azure storage account and created containers for **permissions** and **sample-queries** and copied over the permissions and sample-queries files from this repo: https://github.com/microsoftgraph/microsoft-graph-devx-content over to your respective Azure containers?

**Comment by smerkx** [comment]
> @smerkx have you set up your Azure storage account and created containers for **permissions** and **sample-queries** and copied over the permissions and sample-queries files from this repo: https://github.com/microsoftgraph/microsoft-graph-devx-content over to your respective Azure containers?

Thanks, I missed that repo...

With this info, I should be able to get things up-and-running easily.

Actually, now that I have the permissions json file, I can achieve my goal with a couple of lines of Powershell, no need to start hacking away at the REST API services...

For a security assessment, I want to know what Graph API calls are exposed when permission <x> is granted to a 3rd party app, so I need some kind reverse lookup. Seeing the layout of the json file, that is trivial to achieve...
