### ISSUE TITLE
Missing Permission: External Connections Endpoints

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-devx-api#810]
- [ ] [List External Connections](https://docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-1.0&tabs=http) requires `ExternalConnection.ReadWrite.OwnedBy` DevX returns HTTP 404
- [ ] [Get External Groups]( https://docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&tabs=http) requires `ExternalItem.ReadWrite.OwnedBy, ExternalItem.ReadWrite.All` DevX returns HTTP 404
- [ ] [Get Schema](https://docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&tabs=csharp) requires `ExternalConnection.ReadWrite.OwnedBy`
- [ ] Odd DevX Behavior for:- `/external/connections` and `external/connections/{connection-id}`
GET External Connections with an identifier for the external connection returns permissions however, removing the identifier returns HTTP 404
```http
GET https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/external/connections/raptor&method=GET&scopeType=Application


[
    {
        "value": "ExternalConnection.ReadWrite.OwnedBy",
        "consentDisplayName": "Read and write external connections",
        "consentDescription": "Allows the app to read and write external connections without a signed-in user. The app can only read and write external connections that it is authorized to, or it can create new external connections. ",
        "isAdmin": false
    }
]
```
 list-externalconnection-csharp-v1-executes
```http
GET https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/external/connections&method=GET&scopeType=Application

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-1a0e577147b0744591d1109f14a1ec9d-395eedb80174fe4b-00"
}
```

**Comment by fey101** [comment]
Fixed as appears below and also confirmed that the test `list-externalconnection-csharp-V1` is in our Csharp V1 Execution tests passing/stable list
![image](https://user-images.githubusercontent.com/11347476/204586916-c3424b89-e624-4b08-953d-71127e06db98.png)
