### ISSUE TITLE
Example Ids Interpreted as Parts of Generated Path Instead of As Input

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#836]
Example:
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var delta = await graphClient.Me.Tasks.Lists.AAMkAGVjMzJmMWZjLTgyYjgtNGIyNi1hOGQ0LWRjMjNmMGRmOWNiYQAuAAAAAAAboFsPFj7gQpLAt-6oC2JgAQCQ47jE5P--SoVECqTdM17RAAAB4mDIAAA=.Tasks.Delta
	.Request()
	.GetAsync();
```

**To Reproduce**
See the following docs pages:
- https://docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&tabs=csharp#request
- https://docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&tabs=csharp#request

**Screenshots**
![image](https://user-images.githubusercontent.com/11347476/146617887-3058b3ba-12b1-426e-83d7-5ab5cbb8ea29.png)

**Comment by andrueastman** [comment]
This is no longer an issue for OpenAPI based snippet generation. Furthermore, relevant APIs referenced has been deprecated and not present in metadata.
