### ISSUE TITLE
Missing Permission: ExternalConnection.ReadWrite.OwnedBy

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-devx-api#843]
**Describe the bug**
List External Connections as Described [here ](https://docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-1.0&tabs=http) requires `ExternalConnection.ReadWrite.OwnedBy` which cannot be acquired in Graph Explorer since its not present in permissions list. 

**To Reproduce**
1. Go to Graph Explorer
2. Enter https://graph.microsoft.com/v1.0/external/connections in the URL box
3. Click on `Modify Permissions Tab`
4. List pf Permissions will be Empty
5. Click on `Open Permissions Panel`, search for `ExternalConnection.ReadWrite.OwnedBy` 
6. No results will be returned. 
**Expected behavior**
I expect to see `ExternalConnection.ReadWrite.OwnedBy` in the list of permissions available.
**Screenshots**
![image](https://user-images.githubusercontent.com/1641829/148520456-e460639f-7241-47c5-a6e0-e6db05223f1d.png)
**Desktop (please complete the following information):**
 - OS Windows 11
 - Browser: Edge
 - Version: Version 96.0.1054.62 (Official build) (64-bit)

**Additional context**
Searching through DevX API Permissions it seems to be missing from the list. 
![image](https://user-images.githubusercontent.com/1641829/148521038-f24f56f6-cd3c-46ec-bc2a-887ff85ce093.png)

Related to https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1334

**Comment by irvinesunday** [comment]
@georgend the target permission you expect is an `Application` permission and can be retrieved from DevX API via the uri: https://graphexplorerapi.azurewebsites.net/permissions?scopetype=Application
Graph Explorer only requests for `DelegatedWork` permissions via the call: https://graphexplorerapi.azurewebsites.net/permissions?scopetype=DelegatedWork which is same as https://graphexplorerapi.azurewebsites.net/permissions as `DelegatedWork` is the default scope type returned by DevX API when none is specified.

**Comment by fey101** [comment]
@irvinesunday , the above is both a delegated and an application permission. So it should have been appearing in the list. under modify permissions. This seems fixed though as per below screenshot
![image](https://user-images.githubusercontent.com/11347476/172637228-d69b8db3-119e-4357-a167-512fa99a77ec.png)
