### ISSUE TITLE
Investigate rise in failure anomalies 

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoftgraph/microsoft-graph-devx-api#851]
The `OpenApi/Get` endpoint has been recording a lot of failed requests coming in.
The failure rate has spiked to 74% over the last 12hrs which is quite high compared to the normal failure rate of 28.4%
As per our telemetry board, the most prevalent error codes are error `404` and `400s`.
This ticket serves to investigate the root cause of the failures and come up with a solution to reduce the incoming errors.

**Comment by zengin** [comment]
possibly related: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1335

**Comment by MaggieKimani1** [comment]
> possibly related: [microsoftgraph/microsoft-graph-explorer-v4#1335](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1335)

Thank you for raising this. Investigating it further..

**Comment by zengin** [comment]
I think it is relatively cheap to validate the version information on the client side to avoid calls that are guaranteed to fail. Currently GE is sending version information by extracting the first 4 letters that comes after graph.microsoft.com, e.g. `graph.microsoft.com/randomversion` sends `rand` as the version.

GE already has a constant list of versions, i.e. the version dropdown. I think we should add that validation to avoid the roundtrip to the service.

From DevX API standpoint, I think the service is doing the right thing and returning a 400 response for invalid version parameters.

cc: @thewahome

**Comment by RabebOthmani** [comment]
@irvinesunday from your comment above, I believe the issue is not solved. Is that correct? In which case, let's prioritize this.

**Comment by zengin** [comment]
@irvinesunday @MaggieKimani1 is there a chance we can see the correlation of this data with the service startup events? As part of an incident last week, I had to restart the service and observed high latency and larger request times right after that, which settled after about half an hour. It looks like we can do optimizations around service startup (this is likely a cache warm-up issue). I am not sure if it is related to the problem raised here, but it can be a potential place for investigation.

I will create a separate issue from this comment if they turn out to be unrelated.
