### ISSUE TITLE
AddAsync method appended to a online meeting registration which is not a collection

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#857]
**Describe the bug**
Generally `AddAsync` should be for collections. Then `CreateAsync` for a simple entity type. Then you might see PostAsync when its neither(e.g an action)

Related documentation where erroneous snippet can be found https://docs.microsoft.com/en-us/graph/api/externalmeetingregistration-post?view=graph-rest-beta&tabs=csharp#request

**Expected**
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var meetingRegistration = new ExternalMeetingRegistration
{
	AllowedRegistrant = MeetingAudience.Everyone
};

await graphClient.Me.OnlineMeetings["{onlineMeeting-id}"].Registration
	.Request()
	.CreateAsync(meetingRegistration);
```
**Screenshot of erroneous snippet**
![image](https://user-images.githubusercontent.com/11347476/150339093-9744b555-6ad7-4c2e-a8c6-208b7c21e497.png)

**Comment by andrueastman** [comment]
This is no longer an issue for openApi snippet generation which uses the method to determine the method name. 
However, the snippet specifically fails to generated due to missing POST method in the API tracked via https://github.com/microsoftgraph/msgraph-metadata/issues/405
