### ISSUE TITLE
Intermittent failure of snippet endpoint

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-devx-api#858]
**Describe the bug**
From Graph Explorer, sometimes the snippets fail to load

![image](https://user-images.githubusercontent.com/9458079/150350518-7ae969f0-e955-4e21-acbe-ae8d1ff831bd.png)

**To Reproduce**
Go to[ Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and try loading the code snippet tab, switch from one tab to another

**Expected behavior**
The snippet tab on GE should be able to load results

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by RabebOthmani** [comment]
This issue is still happening (unless the fix is not deployed!!) 
@adhiambovivian 

<img width="848" alt="still happening" src="https://user-images.githubusercontent.com/5781590/152834378-86481657-bb96-4e18-a3d1-41cf17dd17cd.png">
