### ISSUE TITLE
EducationSchoolUser missing permission scopes

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/microsoft-graph-devx-api#917]
Missing Permission scopes
https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/928

**Comment by irvinesunday** [comment]
DevX API retrieves permissions from the below files:
v1.0: https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-v1.0.json
beta: https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-beta.json

The provided url: `/education/schools/{educationSchool-id}/users` doesn't exist in the above files.

**Comment by timayabi2020** [comment]
> DevX API retrieves permissions from the below files: v1.0: https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-v1.0.json beta: https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-devx-content/dev/permissions/permissions-beta.json
> 
> The provided url: `/education/schools/{educationSchool-id}/users` doesn't exist in the above files.

@irvinesunday  thanks. What is required or rather who should I contact to have those permissions in those files?

**Comment by irvinesunday** [comment]
Sorry @timayabi2020, I provided the wrong info. above. The provided resource only accepts Application permissions, not Delegated permissions. See the doc.: https://docs.microsoft.com/en-us/graph/api/educationschool-list-users?view=graph-rest-1.0&tabs=http
This uri will give you the expected App permissions: https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/education/schools/{educationSchool-id}/users&method=GET&scopeType=Application

**Comment by timayabi2020** [comment]
> Sorry @timayabi2020, I provided the wrong info. above. The provided resource only accepts Application permissions, not Delegated permissions. See the doc.: https://docs.microsoft.com/en-us/graph/api/educationschool-list-users?view=graph-rest-1.0&tabs=http This uri will give you the expected App permissions: [https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/education/schools/{educationSchool-id}/users&method=GET&scopeType=Application](https://graphexplorerapi.azurewebsites.net/permissions?requesturl=/education/schools/%7BeducationSchool-id%7D/users&method=GET&scopeType=Application)

Thanks Sunday.
I've used the application permissions and it has worked
