### ISSUE TITLE
OpenAPI code generators timing out 

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/microsoft-graph-devx-api#927]
**Describe the bug**
Investigate failing Snippet generation for Typescript and Go

Possible Causes: 
Failing SSL Validation when attempting to download OpenAPI yml file

Sample Run: 
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=71427&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=e19b279f-2a41-5171-6e52-a43b27738914

error log 

```
Exception while processing /tmp/86314ac5-8d41-42d3-99f4-f8c0d3a6cfed/get-organization-1-beta-httpSnippet.The SSL connection could not be established, see inner exception.   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
```

**Comment by ddyett** [comment]
@rkodev is this work still blocked, if so what's the block

**Comment by rkodev** [comment]
@ddyett We are still getting timeouts. Updated the ran to tests generation without validating SSL certificates as well as increasing timeouts but the validation is still failing https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=72095&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by zengin** [comment]
@rkodev I had a quick look at this issue, this doesn't seem to be failing because of SSL per se, the inner exception is still a timeout. I think, it might be worth looking into how lazy initialization is set up for open api documents. Ideally the document should be initialized only once, but it calls an async method in a synchronous manner through GetAwaiter().GetResult(). Please reach out to me if you want to investigate this together.

**Comment by rkodev** [comment]
@zengin Thank you for this, removing the lazy initialization worked. Here is the test run https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=72307&view=results

**Comment by rkodev** [comment]
@zengin Here is the PR for the changes https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/934

**Comment by baywet** [comment]
After chatting with @rkodev it seems we're trying to tackle 3 different problems here with Lazy:

- cache invalidation/freshness
- thread safety
- transient errors handling

Lazy is not designed to handle that and will not solve our issues here.

## Cache invalidation

Devx api lives in an application pool, which we don't control the lifecycle of (besides deploying/restarting the web app).
Devx api also doesn't control/is not notified, when those files changes.
This means that at any given time the cached value, as implemented today, could be outdated, serving a subpar experience. And this is on top of race conditions and caching transient errors (expanding on those aspects below)

There are a couple of things we can take advantage of: Cache control and Etag.

1. When the cache is empty, GET https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml return a 200 OK + bytes + Etag (value) + Cache-control max-age: (value in second), the service should not only "keep" the binary content, but also use the etag as metadata, and the cache control to calculate a cache expiration date.
2. When the cache is hydrated, if the expiration date is not expired, serve that
3. If the expiration date is expired, GET https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml with If-None-Match <Etag Value>
4. If we get a 304, update the expiration date, and serve the value we already have in memory
5. if we get a 200, update the expiration date, the etag value, the binary value, and serve the new value.

Getting/Caching the information is a single concern and should be implemented in a single "IOpenAPIDocumentProvider" implementation, without mixing other concerns.

## Thread safety/race conditions

Another concern that's been creeping in this overall issue is the thread safety/race conditions. Obviously we don't want multiple thread initializing the obtention/caching at the same time as it is costly, can lead to throttling on the dependency service side and can lead to incoherent states.

Lazy is usually well suited for sync lazy loading, but it's not a thread safety mechanism by default (hence the overload constructors to "tweak that"). However it doesn't play well with async operations, and cache concerns. It also leads to deadlocks/pools starvation when running under a parallel foreach depending on the settings, like we've seen with the snippets generation app.
My argument here is we should simply replace it by a proxy design pattern, and simply re-implement "IOpenAPIDocumentProvider" with locks.

## Transient errors handling

Another concerns that has made this issue more complex to tackle is the fact that the OpenAPI document obtention can run into a transient statuses (429's, 504's...), or errors (connection drop). If I believe httpclient handles the later (remains to be checked and to double check whether our client is properly configured), it doesn't handle the former.
For that we could either use middleware like we do in the Graph client, or another proxy design pattern implementation or AOP with something like Poly.

Through a composition of all those layers, I believe we can properly handle the 3 separate but intricate concerns that are caching/obtention, thread safety and transient errors while maintaining a clean API surface for the dependent services (OpenApiSnippetsGenerator and others).

Lastly, we should rely on dependency injection and service tagging to avoid using duplicate instances.
