### ISSUE TITLE
Expand Segment Contains Unincluded Property

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#938]
```Http
GET https://graph.microsoft.com/beta/me/events/AAMkADAGAADDdm4NAAA=/?$select=subject,start,end,occurrenceId,exceptionOccurrences,cancelledOccurrences&$expand=exceptionOccurrences
```
In above, `cancelledOccurrences` is not included in `expand` option but in generated C# snippet below, it includes it in the expand option
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var @event = await graphClient.Me.Events["{event-id}"]
	.Request()
	.Expand("exceptionOccurrences,cancelledOccurrences")
	.Select("subject,start,end,occurrenceId,exceptionOccurrences,cancelledOccurrences")
	.GetAsync();
```

Docs link: https://docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&tabs=csharp#request-3

Snapshot:
![image](https://user-images.githubusercontent.com/11347476/162981291-73f5a84a-d612-4bf5-91f4-6c797e8657fc.png)

**Comment by fey101** [comment]
Similarly, in the following snippet "roleDefinitionId" is not included in the expand query params but in C#, JS, and Java snippets, it is included. However Go seems to have captured it right.
```http
GET https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleRequests?$select=principalId,action,roleDefinitionId&$expand=roleDefinition,activatedUsing,principal,targetSchedule
```
Generated C# Snippet:
![image](https://user-images.githubusercontent.com/11347476/167573773-9bfc92d8-7b6a-40c5-bbc6-aecc6dfbbcd8.png)

**Comment by zengin** [comment]
This is stale and resolved with the new version of SDK. @irvinesunday, @adhiambovivian do you mind closing this for me? I don't seem to have issue closing privileges anymore.
