### ISSUE TITLE
Have `OpenApiConvertSettings` configurable for each style

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#956]
Different styles (Plain, PowerShell, PowerPlatform. GEAutocomplete) have different OpenAPI document style requirements. What works for one doesn't work for another. We need to make the `OpenApiConvertSettings` configurable in the `OpenAPIStyleOptions` class so that each style can customize the way it wants the conversion of OpenAPI configured. We would also need to consider the below:
- We need to keep in mind that this might mean having different caches of OpenAPI documents for the different styles.
- We need to keep track of stale OpenAPI document caches and how to refresh them.
- Can we move this functionality to the OpenAPI.NET/Hidi project so that it is re-usable there as well? 

Related to: https://github.com/microsoft/OpenAPI.NET/issues/830

**Comment by adhiambovivian** [comment]
@millicentachieng  this should be tied to the work you are doing around expansion of entities eg drive that's not applicable to powershell

**Comment by millicentachieng** [comment]
@adhiambovivian yes. @MaryannGitonga and @irvinesunday I'm taking the issue from you.
