### ISSUE TITLE
Missing Code Snippets (Invalid Tab Group)

### ISSUE THREAD

**Issue by v-emilypr** [microsoftgraph/microsoft-graph-devx-api#962]
**Describe the bug**
Multiple files in the microsoft-graph-docs repo contain invalid-tab-group warnings related to missing code snippets that should be auto-generated. Filing issue per @andrueastman.

**To Reproduce**
1. Go to 'https://github.com/microsoftgraph/microsoft-graph-docs/pull/16644'
2. Click on 'Show all checks, Open Publishing Build Report details link'
3. Scroll down to 'Validated Files'
4. See errors

**Expected behavior**
The invalid-tab-group error is being generated on the open publishing build report due to missing code snippets within the articles. 

**Additional context**
Additional PR's containing invalid-tab-group warnings will be linked within the PR listed above.

**Comment by Lauragra** [comment]
@v-emilypr , would you mind moving this issue to the microsoft-graph-docs repo? If you use the feedback control on one of the affected topics on the site, it won't get closed by our automation, and I can assign it to Andrew.

**Comment by Lauragra** [comment]
> @v-emilypr , would you mind moving this issue to the microsoft-graph-docs repo? If you use the feedback control on one of the affected topics on the site, it won't get closed by our automation, and I can assign it to Andrew.

Oh wait, nvm, Andrew asked for it in the repo so I assume he'll self-assign.

**Comment by millicentachieng** [comment]
This was done in this PR https://github.com/OneDrive/apidoctor/pull/139. The PR addresses the following:
- Ensure all methods in the document have tabs for all languages in the set
- Methods that do not have a snippet for a particular language have the information Snippet not available within the tab
