### ISSUE TITLE
Http String Not Mapped Into Metadata-Existing Enum Type

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-devx-api#983]
**Describe the bug**
In example below, the expected value of `Action` should be `Action = UnifiedRoleScheduleRequestActions.adminRemove` , but it's instead `Action = "adminRemove",`

Docs Link: https://docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleeligibilityschedulerequests?view=graph-rest-1.0&tabs=csharp#request-1

Http Request:
```http
POST https://graph.microsoft.com/beta/roleManagement/directory/roleEligibilityScheduleRequests
Content-Type: application/json

{
    "action": "adminRemove",
    "roleDefinitionId": "8424c6f0-a189-499e-bbd0-26c1753c96d4",
    "directoryScopeId": "/",
    "principalId": "071cc716-8147-4397-a5ba-b2105951cc0b"
}
```

Generated C# Snippet:
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var unifiedRoleEligibilityScheduleRequest = new UnifiedRoleEligibilityScheduleRequestObject
{
	Action = "adminRemove",
	RoleDefinitionId = "8424c6f0-a189-499e-bbd0-26c1753c96d4",
	DirectoryScopeId = "/",
	PrincipalId = "071cc716-8147-4397-a5ba-b2105951cc0b"
};

await graphClient.RoleManagement.Directory.RoleEligibilityScheduleRequests
	.Request()
	.AddAsync(unifiedRoleEligibilityScheduleRequest);
```

Expected C# Code:
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var unifiedRoleEligibilityScheduleRequest = new UnifiedRoleEligibilityScheduleRequestObject
{
	Action = UnifiedRoleScheduleRequestActions.adminRemove,
	RoleDefinitionId = "8424c6f0-a189-499e-bbd0-26c1753c96d4",
	DirectoryScopeId = "/",
	PrincipalId = "071cc716-8147-4397-a5ba-b2105951cc0b"
};

await graphClient.RoleManagement.Directory.RoleEligibilityScheduleRequests
	.Request()
	.AddAsync(unifiedRoleEligibilityScheduleRequest);
```

Metadata description:
```CSDL
<EnumType Name="unifiedRoleScheduleRequestActions">
    <Member Name="adminAssign" Value="1"/>
    <Member Name="adminUpdate" Value="2"/>
    <Member Name="adminRemove" Value="3"/>
    <Member Name="selfActivate" Value="4"/>
    <Member Name="selfDeactivate" Value="5"/>
    <Member Name="adminExtend" Value="6"/>
    <Member Name="adminRenew" Value="7"/>
    <Member Name="selfExtend" Value="8"/>
    <Member Name="selfRenew" Value="9"/>
    <Member Name="unknownFutureValue" Value="10"/>
</EnumType>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11347476/167503839-f44ae5dc-4f1e-48b2-a3a8-46a99e68ad42.png)

**Comment by andrueastman** [comment]
Hey @fey101,

The `unifiedRoleScheduleRequestActions` enum seems to have now been removed and the property changed to a string. 

![image](https://user-images.githubusercontent.com/6464005/167599686-b45089d2-1e54-428a-a2ad-151191fe981c.png)

**Comment by andrueastman** [comment]
It looks like this is a doc issue. 

The first http example in the docs calls the v1.0 endpoint while the second example calls the beta endpoint. 
Beta metadata has the property as string while v1.0 metadata has the property as an enum thus explaining the inconsistency in the snippets. 

We would need to change the url in the http example from 

```http
https://graph.microsoft.com/beta/roleManagement/directory/roleEligibilityScheduleRequests
```
to

```http
https://graph.microsoft.com/v1.0/roleManagement/directory/roleEligibilityScheduleRequests
```

**Comment by fey101** [comment]
![image](https://github.com/microsoftgraph/microsoft-graph-devx-api/assets/11347476/5225fbb6-66af-463c-973b-2b6aad6a823f)

From the docs this appears fixed shown above. This is also fixed as per raptor reports.
